package com.ints.common.model;

public class TaAdminMng {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer adminMngIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String adminId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_name
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String adminName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_pass
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String adminPass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_auth
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String adminAuth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_dept
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String adminDept;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ADMIN_MNG.admin_title
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String adminTitle;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_mng_idx
	 * @return  the value of TA_ADMIN_MNG.admin_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getAdminMngIdx() {
		return adminMngIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_mng_idx
	 * @param adminMngIdx  the value for TA_ADMIN_MNG.admin_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminMngIdx(Integer adminMngIdx) {
		this.adminMngIdx = adminMngIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_id
	 * @return  the value of TA_ADMIN_MNG.admin_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAdminId() {
		return adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_id
	 * @param adminId  the value for TA_ADMIN_MNG.admin_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_name
	 * @return  the value of TA_ADMIN_MNG.admin_name
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAdminName() {
		return adminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_name
	 * @param adminName  the value for TA_ADMIN_MNG.admin_name
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_pass
	 * @return  the value of TA_ADMIN_MNG.admin_pass
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAdminPass() {
		return adminPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_pass
	 * @param adminPass  the value for TA_ADMIN_MNG.admin_pass
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminPass(String adminPass) {
		this.adminPass = adminPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_auth
	 * @return  the value of TA_ADMIN_MNG.admin_auth
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAdminAuth() {
		return adminAuth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_auth
	 * @param adminAuth  the value for TA_ADMIN_MNG.admin_auth
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminAuth(String adminAuth) {
		this.adminAuth = adminAuth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_dept
	 * @return  the value of TA_ADMIN_MNG.admin_dept
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAdminDept() {
		return adminDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_dept
	 * @param adminDept  the value for TA_ADMIN_MNG.admin_dept
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminDept(String adminDept) {
		this.adminDept = adminDept;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ADMIN_MNG.admin_title
	 * @return  the value of TA_ADMIN_MNG.admin_title
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAdminTitle() {
		return adminTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ADMIN_MNG.admin_title
	 * @param adminTitle  the value for TA_ADMIN_MNG.admin_title
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAdminTitle(String adminTitle) {
		this.adminTitle = adminTitle;
	}
}