package com.ints.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TaAskMngExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public TaAskMngExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAskMngIdxIsNull() {
			addCriterion("ask_mng_idx is null");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxIsNotNull() {
			addCriterion("ask_mng_idx is not null");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxEqualTo(Integer value) {
			addCriterion("ask_mng_idx =", value, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxNotEqualTo(Integer value) {
			addCriterion("ask_mng_idx <>", value, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxGreaterThan(Integer value) {
			addCriterion("ask_mng_idx >", value, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("ask_mng_idx >=", value, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxLessThan(Integer value) {
			addCriterion("ask_mng_idx <", value, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxLessThanOrEqualTo(Integer value) {
			addCriterion("ask_mng_idx <=", value, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxIn(List<Integer> values) {
			addCriterion("ask_mng_idx in", values, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxNotIn(List<Integer> values) {
			addCriterion("ask_mng_idx not in", values, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxBetween(Integer value1, Integer value2) {
			addCriterion("ask_mng_idx between", value1, value2, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andAskMngIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("ask_mng_idx not between", value1, value2, "askMngIdx");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNull() {
			addCriterion("subject is null");
			return (Criteria) this;
		}

		public Criteria andSubjectIsNotNull() {
			addCriterion("subject is not null");
			return (Criteria) this;
		}

		public Criteria andSubjectEqualTo(String value) {
			addCriterion("subject =", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotEqualTo(String value) {
			addCriterion("subject <>", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThan(String value) {
			addCriterion("subject >", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectGreaterThanOrEqualTo(String value) {
			addCriterion("subject >=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThan(String value) {
			addCriterion("subject <", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLessThanOrEqualTo(String value) {
			addCriterion("subject <=", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectLike(String value) {
			addCriterion("subject like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotLike(String value) {
			addCriterion("subject not like", value, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectIn(List<String> values) {
			addCriterion("subject in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotIn(List<String> values) {
			addCriterion("subject not in", values, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectBetween(String value1, String value2) {
			addCriterion("subject between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andSubjectNotBetween(String value1, String value2) {
			addCriterion("subject not between", value1, value2, "subject");
			return (Criteria) this;
		}

		public Criteria andUseIsIsNull() {
			addCriterion("use_is is null");
			return (Criteria) this;
		}

		public Criteria andUseIsIsNotNull() {
			addCriterion("use_is is not null");
			return (Criteria) this;
		}

		public Criteria andUseIsEqualTo(Integer value) {
			addCriterion("use_is =", value, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsNotEqualTo(Integer value) {
			addCriterion("use_is <>", value, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsGreaterThan(Integer value) {
			addCriterion("use_is >", value, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsGreaterThanOrEqualTo(Integer value) {
			addCriterion("use_is >=", value, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsLessThan(Integer value) {
			addCriterion("use_is <", value, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsLessThanOrEqualTo(Integer value) {
			addCriterion("use_is <=", value, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsIn(List<Integer> values) {
			addCriterion("use_is in", values, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsNotIn(List<Integer> values) {
			addCriterion("use_is not in", values, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsBetween(Integer value1, Integer value2) {
			addCriterion("use_is between", value1, value2, "useIs");
			return (Criteria) this;
		}

		public Criteria andUseIsNotBetween(Integer value1, Integer value2) {
			addCriterion("use_is not between", value1, value2, "useIs");
			return (Criteria) this;
		}

		public Criteria andThumbIsNull() {
			addCriterion("thumb is null");
			return (Criteria) this;
		}

		public Criteria andThumbIsNotNull() {
			addCriterion("thumb is not null");
			return (Criteria) this;
		}

		public Criteria andThumbEqualTo(String value) {
			addCriterion("thumb =", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotEqualTo(String value) {
			addCriterion("thumb <>", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbGreaterThan(String value) {
			addCriterion("thumb >", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbGreaterThanOrEqualTo(String value) {
			addCriterion("thumb >=", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbLessThan(String value) {
			addCriterion("thumb <", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbLessThanOrEqualTo(String value) {
			addCriterion("thumb <=", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbLike(String value) {
			addCriterion("thumb like", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotLike(String value) {
			addCriterion("thumb not like", value, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbIn(List<String> values) {
			addCriterion("thumb in", values, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotIn(List<String> values) {
			addCriterion("thumb not in", values, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbBetween(String value1, String value2) {
			addCriterion("thumb between", value1, value2, "thumb");
			return (Criteria) this;
		}

		public Criteria andThumbNotBetween(String value1, String value2) {
			addCriterion("thumb not between", value1, value2, "thumb");
			return (Criteria) this;
		}

		public Criteria andAttatchFileIsNull() {
			addCriterion("attatch_file is null");
			return (Criteria) this;
		}

		public Criteria andAttatchFileIsNotNull() {
			addCriterion("attatch_file is not null");
			return (Criteria) this;
		}

		public Criteria andAttatchFileEqualTo(String value) {
			addCriterion("attatch_file =", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileNotEqualTo(String value) {
			addCriterion("attatch_file <>", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileGreaterThan(String value) {
			addCriterion("attatch_file >", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileGreaterThanOrEqualTo(String value) {
			addCriterion("attatch_file >=", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileLessThan(String value) {
			addCriterion("attatch_file <", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileLessThanOrEqualTo(String value) {
			addCriterion("attatch_file <=", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileLike(String value) {
			addCriterion("attatch_file like", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileNotLike(String value) {
			addCriterion("attatch_file not like", value, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileIn(List<String> values) {
			addCriterion("attatch_file in", values, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileNotIn(List<String> values) {
			addCriterion("attatch_file not in", values, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileBetween(String value1, String value2) {
			addCriterion("attatch_file between", value1, value2, "attatchFile");
			return (Criteria) this;
		}

		public Criteria andAttatchFileNotBetween(String value1, String value2) {
			addCriterion("attatch_file not between", value1, value2,
					"attatchFile");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2,
					"createDate");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNull() {
			addCriterion("create_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNotNull() {
			addCriterion("create_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateIdEqualTo(String value) {
			addCriterion("create_id =", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotEqualTo(String value) {
			addCriterion("create_id <>", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThan(String value) {
			addCriterion("create_id >", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThanOrEqualTo(String value) {
			addCriterion("create_id >=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThan(String value) {
			addCriterion("create_id <", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThanOrEqualTo(String value) {
			addCriterion("create_id <=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLike(String value) {
			addCriterion("create_id like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotLike(String value) {
			addCriterion("create_id not like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdIn(List<String> values) {
			addCriterion("create_id in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotIn(List<String> values) {
			addCriterion("create_id not in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdBetween(String value1, String value2) {
			addCriterion("create_id between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotBetween(String value1, String value2) {
			addCriterion("create_id not between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andReplyIsIsNull() {
			addCriterion("reply_is is null");
			return (Criteria) this;
		}

		public Criteria andReplyIsIsNotNull() {
			addCriterion("reply_is is not null");
			return (Criteria) this;
		}

		public Criteria andReplyIsEqualTo(Integer value) {
			addCriterion("reply_is =", value, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsNotEqualTo(Integer value) {
			addCriterion("reply_is <>", value, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsGreaterThan(Integer value) {
			addCriterion("reply_is >", value, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsGreaterThanOrEqualTo(Integer value) {
			addCriterion("reply_is >=", value, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsLessThan(Integer value) {
			addCriterion("reply_is <", value, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsLessThanOrEqualTo(Integer value) {
			addCriterion("reply_is <=", value, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsIn(List<Integer> values) {
			addCriterion("reply_is in", values, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsNotIn(List<Integer> values) {
			addCriterion("reply_is not in", values, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsBetween(Integer value1, Integer value2) {
			addCriterion("reply_is between", value1, value2, "replyIs");
			return (Criteria) this;
		}

		public Criteria andReplyIsNotBetween(Integer value1, Integer value2) {
			addCriterion("reply_is not between", value1, value2, "replyIs");
			return (Criteria) this;
		}

		public Criteria andHitcountIsNull() {
			addCriterion("hitcount is null");
			return (Criteria) this;
		}

		public Criteria andHitcountIsNotNull() {
			addCriterion("hitcount is not null");
			return (Criteria) this;
		}

		public Criteria andHitcountEqualTo(Integer value) {
			addCriterion("hitcount =", value, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountNotEqualTo(Integer value) {
			addCriterion("hitcount <>", value, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountGreaterThan(Integer value) {
			addCriterion("hitcount >", value, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("hitcount >=", value, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountLessThan(Integer value) {
			addCriterion("hitcount <", value, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountLessThanOrEqualTo(Integer value) {
			addCriterion("hitcount <=", value, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountIn(List<Integer> values) {
			addCriterion("hitcount in", values, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountNotIn(List<Integer> values) {
			addCriterion("hitcount not in", values, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountBetween(Integer value1, Integer value2) {
			addCriterion("hitcount between", value1, value2, "hitcount");
			return (Criteria) this;
		}

		public Criteria andHitcountNotBetween(Integer value1, Integer value2) {
			addCriterion("hitcount not between", value1, value2, "hitcount");
			return (Criteria) this;
		}

		public Criteria andResponseIsNull() {
			addCriterion("response is null");
			return (Criteria) this;
		}

		public Criteria andResponseIsNotNull() {
			addCriterion("response is not null");
			return (Criteria) this;
		}

		public Criteria andResponseEqualTo(String value) {
			addCriterion("response =", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseNotEqualTo(String value) {
			addCriterion("response <>", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseGreaterThan(String value) {
			addCriterion("response >", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseGreaterThanOrEqualTo(String value) {
			addCriterion("response >=", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseLessThan(String value) {
			addCriterion("response <", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseLessThanOrEqualTo(String value) {
			addCriterion("response <=", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseLike(String value) {
			addCriterion("response like", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseNotLike(String value) {
			addCriterion("response not like", value, "response");
			return (Criteria) this;
		}

		public Criteria andResponseIn(List<String> values) {
			addCriterion("response in", values, "response");
			return (Criteria) this;
		}

		public Criteria andResponseNotIn(List<String> values) {
			addCriterion("response not in", values, "response");
			return (Criteria) this;
		}

		public Criteria andResponseBetween(String value1, String value2) {
			addCriterion("response between", value1, value2, "response");
			return (Criteria) this;
		}

		public Criteria andResponseNotBetween(String value1, String value2) {
			addCriterion("response not between", value1, value2, "response");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateIsNull() {
			addCriterion("response_create_date is null");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateIsNotNull() {
			addCriterion("response_create_date is not null");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateEqualTo(Date value) {
			addCriterion("response_create_date =", value, "responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateNotEqualTo(Date value) {
			addCriterion("response_create_date <>", value, "responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateGreaterThan(Date value) {
			addCriterion("response_create_date >", value, "responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("response_create_date >=", value, "responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateLessThan(Date value) {
			addCriterion("response_create_date <", value, "responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("response_create_date <=", value, "responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateIn(List<Date> values) {
			addCriterion("response_create_date in", values,
					"responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateNotIn(List<Date> values) {
			addCriterion("response_create_date not in", values,
					"responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateBetween(Date value1, Date value2) {
			addCriterion("response_create_date between", value1, value2,
					"responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("response_create_date not between", value1, value2,
					"responseCreateDate");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdIsNull() {
			addCriterion("response_create_id is null");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdIsNotNull() {
			addCriterion("response_create_id is not null");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdEqualTo(String value) {
			addCriterion("response_create_id =", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdNotEqualTo(String value) {
			addCriterion("response_create_id <>", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdGreaterThan(String value) {
			addCriterion("response_create_id >", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdGreaterThanOrEqualTo(String value) {
			addCriterion("response_create_id >=", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdLessThan(String value) {
			addCriterion("response_create_id <", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdLessThanOrEqualTo(String value) {
			addCriterion("response_create_id <=", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdLike(String value) {
			addCriterion("response_create_id like", value, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdNotLike(String value) {
			addCriterion("response_create_id not like", value,
					"responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdIn(List<String> values) {
			addCriterion("response_create_id in", values, "responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdNotIn(List<String> values) {
			addCriterion("response_create_id not in", values,
					"responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdBetween(String value1, String value2) {
			addCriterion("response_create_id between", value1, value2,
					"responseCreateId");
			return (Criteria) this;
		}

		public Criteria andResponseCreateIdNotBetween(String value1,
				String value2) {
			addCriterion("response_create_id not between", value1, value2,
					"responseCreateId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_ASK_MNG
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 10 18:47:41 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}