package com.ints.common.model;

import java.util.Date;

public class TaAskMng {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.ask_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer askMngIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.subject
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.use_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer useIs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.thumb
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String thumb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.attatch_file
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String attatchFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.reply_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer replyIs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.hitcount
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer hitcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.response
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String response;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.response_create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date responseCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.response_create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String responseCreateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_ASK_MNG.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.ask_mng_idx
	 * @return  the value of TA_ASK_MNG.ask_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getAskMngIdx() {
		return askMngIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.ask_mng_idx
	 * @param askMngIdx  the value for TA_ASK_MNG.ask_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAskMngIdx(Integer askMngIdx) {
		this.askMngIdx = askMngIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.subject
	 * @return  the value of TA_ASK_MNG.subject
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.subject
	 * @param subject  the value for TA_ASK_MNG.subject
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.use_is
	 * @return  the value of TA_ASK_MNG.use_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getUseIs() {
		return useIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.use_is
	 * @param useIs  the value for TA_ASK_MNG.use_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setUseIs(Integer useIs) {
		this.useIs = useIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.thumb
	 * @return  the value of TA_ASK_MNG.thumb
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getThumb() {
		return thumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.thumb
	 * @param thumb  the value for TA_ASK_MNG.thumb
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.attatch_file
	 * @return  the value of TA_ASK_MNG.attatch_file
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAttatchFile() {
		return attatchFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.attatch_file
	 * @param attatchFile  the value for TA_ASK_MNG.attatch_file
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAttatchFile(String attatchFile) {
		this.attatchFile = attatchFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.create_date
	 * @return  the value of TA_ASK_MNG.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.create_date
	 * @param createDate  the value for TA_ASK_MNG.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.create_id
	 * @return  the value of TA_ASK_MNG.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.create_id
	 * @param createId  the value for TA_ASK_MNG.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setCreateId(String createId) {
		this.createId = createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.reply_is
	 * @return  the value of TA_ASK_MNG.reply_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getReplyIs() {
		return replyIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.reply_is
	 * @param replyIs  the value for TA_ASK_MNG.reply_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setReplyIs(Integer replyIs) {
		this.replyIs = replyIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.hitcount
	 * @return  the value of TA_ASK_MNG.hitcount
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getHitcount() {
		return hitcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.hitcount
	 * @param hitcount  the value for TA_ASK_MNG.hitcount
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setHitcount(Integer hitcount) {
		this.hitcount = hitcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.response
	 * @return  the value of TA_ASK_MNG.response
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getResponse() {
		return response;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.response
	 * @param response  the value for TA_ASK_MNG.response
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setResponse(String response) {
		this.response = response;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.response_create_date
	 * @return  the value of TA_ASK_MNG.response_create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getResponseCreateDate() {
		return responseCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.response_create_date
	 * @param responseCreateDate  the value for TA_ASK_MNG.response_create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setResponseCreateDate(Date responseCreateDate) {
		this.responseCreateDate = responseCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.response_create_id
	 * @return  the value of TA_ASK_MNG.response_create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getResponseCreateId() {
		return responseCreateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.response_create_id
	 * @param responseCreateId  the value for TA_ASK_MNG.response_create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setResponseCreateId(String responseCreateId) {
		this.responseCreateId = responseCreateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_ASK_MNG.content
	 * @return  the value of TA_ASK_MNG.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_ASK_MNG.content
	 * @param content  the value for TA_ASK_MNG.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}
}