package com.ints.common.model;

import java.util.Date;

public class TaBoardReply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_BOARD_REPLY.reply_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer replyIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_BOARD_REPLY.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_BOARD_REPLY.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_BOARD_REPLY.writing_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer writingIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_BOARD_REPLY.is_answer
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer isAnswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_BOARD_REPLY.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_BOARD_REPLY.reply_idx
	 * @return  the value of TA_BOARD_REPLY.reply_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getReplyIdx() {
		return replyIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_BOARD_REPLY.reply_idx
	 * @param replyIdx  the value for TA_BOARD_REPLY.reply_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setReplyIdx(Integer replyIdx) {
		this.replyIdx = replyIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_BOARD_REPLY.create_date
	 * @return  the value of TA_BOARD_REPLY.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_BOARD_REPLY.create_date
	 * @param createDate  the value for TA_BOARD_REPLY.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_BOARD_REPLY.create_id
	 * @return  the value of TA_BOARD_REPLY.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_BOARD_REPLY.create_id
	 * @param createId  the value for TA_BOARD_REPLY.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setCreateId(String createId) {
		this.createId = createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_BOARD_REPLY.writing_idx
	 * @return  the value of TA_BOARD_REPLY.writing_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getWritingIdx() {
		return writingIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_BOARD_REPLY.writing_idx
	 * @param writingIdx  the value for TA_BOARD_REPLY.writing_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setWritingIdx(Integer writingIdx) {
		this.writingIdx = writingIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_BOARD_REPLY.is_answer
	 * @return  the value of TA_BOARD_REPLY.is_answer
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getIsAnswer() {
		return isAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_BOARD_REPLY.is_answer
	 * @param isAnswer  the value for TA_BOARD_REPLY.is_answer
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setIsAnswer(Integer isAnswer) {
		this.isAnswer = isAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_BOARD_REPLY.content
	 * @return  the value of TA_BOARD_REPLY.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_BOARD_REPLY.content
	 * @param content  the value for TA_BOARD_REPLY.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}
}