package com.ints.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaKrwRequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public TaKrwRequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKrwRequestIdxIsNull() {
            addCriterion("krw_request_idx is null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxIsNotNull() {
            addCriterion("krw_request_idx is not null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxEqualTo(Integer value) {
            addCriterion("krw_request_idx =", value, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxNotEqualTo(Integer value) {
            addCriterion("krw_request_idx <>", value, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxGreaterThan(Integer value) {
            addCriterion("krw_request_idx >", value, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("krw_request_idx >=", value, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxLessThan(Integer value) {
            addCriterion("krw_request_idx <", value, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxLessThanOrEqualTo(Integer value) {
            addCriterion("krw_request_idx <=", value, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxIn(List<Integer> values) {
            addCriterion("krw_request_idx in", values, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxNotIn(List<Integer> values) {
            addCriterion("krw_request_idx not in", values, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxBetween(Integer value1, Integer value2) {
            addCriterion("krw_request_idx between", value1, value2, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("krw_request_idx not between", value1, value2, "krwRequestIdx");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwIsNull() {
            addCriterion("krw_request_krw is null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwIsNotNull() {
            addCriterion("krw_request_krw is not null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwEqualTo(Integer value) {
            addCriterion("krw_request_krw =", value, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwNotEqualTo(Integer value) {
            addCriterion("krw_request_krw <>", value, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwGreaterThan(Integer value) {
            addCriterion("krw_request_krw >", value, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwGreaterThanOrEqualTo(Integer value) {
            addCriterion("krw_request_krw >=", value, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwLessThan(Integer value) {
            addCriterion("krw_request_krw <", value, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwLessThanOrEqualTo(Integer value) {
            addCriterion("krw_request_krw <=", value, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwIn(List<Integer> values) {
            addCriterion("krw_request_krw in", values, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwNotIn(List<Integer> values) {
            addCriterion("krw_request_krw not in", values, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwBetween(Integer value1, Integer value2) {
            addCriterion("krw_request_krw between", value1, value2, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestKrwNotBetween(Integer value1, Integer value2) {
            addCriterion("krw_request_krw not between", value1, value2, "krwRequestKrw");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeIsNull() {
            addCriterion("krw_request_datetime is null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeIsNotNull() {
            addCriterion("krw_request_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeEqualTo(Date value) {
            addCriterion("krw_request_datetime =", value, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeNotEqualTo(Date value) {
            addCriterion("krw_request_datetime <>", value, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeGreaterThan(Date value) {
            addCriterion("krw_request_datetime >", value, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("krw_request_datetime >=", value, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeLessThan(Date value) {
            addCriterion("krw_request_datetime <", value, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("krw_request_datetime <=", value, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeIn(List<Date> values) {
            addCriterion("krw_request_datetime in", values, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeNotIn(List<Date> values) {
            addCriterion("krw_request_datetime not in", values, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeBetween(Date value1, Date value2) {
            addCriterion("krw_request_datetime between", value1, value2, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("krw_request_datetime not between", value1, value2, "krwRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeIsNull() {
            addCriterion("krw_request_response_datetime is null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeIsNotNull() {
            addCriterion("krw_request_response_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeEqualTo(Date value) {
            addCriterion("krw_request_response_datetime =", value, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeNotEqualTo(Date value) {
            addCriterion("krw_request_response_datetime <>", value, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeGreaterThan(Date value) {
            addCriterion("krw_request_response_datetime >", value, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("krw_request_response_datetime >=", value, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeLessThan(Date value) {
            addCriterion("krw_request_response_datetime <", value, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("krw_request_response_datetime <=", value, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeIn(List<Date> values) {
            addCriterion("krw_request_response_datetime in", values, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeNotIn(List<Date> values) {
            addCriterion("krw_request_response_datetime not in", values, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeBetween(Date value1, Date value2) {
            addCriterion("krw_request_response_datetime between", value1, value2, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("krw_request_response_datetime not between", value1, value2, "krwRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdIsNull() {
            addCriterion("krw_request_response_id is null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdIsNotNull() {
            addCriterion("krw_request_response_id is not null");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdEqualTo(String value) {
            addCriterion("krw_request_response_id =", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdNotEqualTo(String value) {
            addCriterion("krw_request_response_id <>", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdGreaterThan(String value) {
            addCriterion("krw_request_response_id >", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdGreaterThanOrEqualTo(String value) {
            addCriterion("krw_request_response_id >=", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdLessThan(String value) {
            addCriterion("krw_request_response_id <", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdLessThanOrEqualTo(String value) {
            addCriterion("krw_request_response_id <=", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdLike(String value) {
            addCriterion("krw_request_response_id like", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdNotLike(String value) {
            addCriterion("krw_request_response_id not like", value, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdIn(List<String> values) {
            addCriterion("krw_request_response_id in", values, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdNotIn(List<String> values) {
            addCriterion("krw_request_response_id not in", values, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdBetween(String value1, String value2) {
            addCriterion("krw_request_response_id between", value1, value2, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andKrwRequestResponseIdNotBetween(String value1, String value2) {
            addCriterion("krw_request_response_id not between", value1, value2, "krwRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andMemberIdxIsNull() {
            addCriterion("member_idx is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdxIsNotNull() {
            addCriterion("member_idx is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdxEqualTo(Integer value) {
            addCriterion("member_idx =", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxNotEqualTo(Integer value) {
            addCriterion("member_idx <>", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxGreaterThan(Integer value) {
            addCriterion("member_idx >", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_idx >=", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxLessThan(Integer value) {
            addCriterion("member_idx <", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxLessThanOrEqualTo(Integer value) {
            addCriterion("member_idx <=", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxIn(List<Integer> values) {
            addCriterion("member_idx in", values, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxNotIn(List<Integer> values) {
            addCriterion("member_idx not in", values, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxBetween(Integer value1, Integer value2) {
            addCriterion("member_idx between", value1, value2, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("member_idx not between", value1, value2, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("member_id like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("member_id not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 29 17:30:03 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}