package com.ints.common.model;

import java.util.Date;

public class TaKrwRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.krw_request_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Integer krwRequestIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.krw_request_krw
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Integer krwRequestKrw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.krw_request_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Date krwRequestDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.krw_request_response_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Date krwRequestResponseDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.krw_request_response_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private String krwRequestResponseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.member_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Integer memberIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_KRW_REQUEST.member_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private String memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.krw_request_idx
     *
     * @return the value of TA_KRW_REQUEST.krw_request_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Integer getKrwRequestIdx() {
        return krwRequestIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.krw_request_idx
     *
     * @param krwRequestIdx the value for TA_KRW_REQUEST.krw_request_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setKrwRequestIdx(Integer krwRequestIdx) {
        this.krwRequestIdx = krwRequestIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.krw_request_krw
     *
     * @return the value of TA_KRW_REQUEST.krw_request_krw
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Integer getKrwRequestKrw() {
        return krwRequestKrw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.krw_request_krw
     *
     * @param krwRequestKrw the value for TA_KRW_REQUEST.krw_request_krw
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setKrwRequestKrw(Integer krwRequestKrw) {
        this.krwRequestKrw = krwRequestKrw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.krw_request_datetime
     *
     * @return the value of TA_KRW_REQUEST.krw_request_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Date getKrwRequestDatetime() {
        return krwRequestDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.krw_request_datetime
     *
     * @param krwRequestDatetime the value for TA_KRW_REQUEST.krw_request_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setKrwRequestDatetime(Date krwRequestDatetime) {
        this.krwRequestDatetime = krwRequestDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.krw_request_response_datetime
     *
     * @return the value of TA_KRW_REQUEST.krw_request_response_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Date getKrwRequestResponseDatetime() {
        return krwRequestResponseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.krw_request_response_datetime
     *
     * @param krwRequestResponseDatetime the value for TA_KRW_REQUEST.krw_request_response_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setKrwRequestResponseDatetime(Date krwRequestResponseDatetime) {
        this.krwRequestResponseDatetime = krwRequestResponseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.krw_request_response_id
     *
     * @return the value of TA_KRW_REQUEST.krw_request_response_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getKrwRequestResponseId() {
        return krwRequestResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.krw_request_response_id
     *
     * @param krwRequestResponseId the value for TA_KRW_REQUEST.krw_request_response_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setKrwRequestResponseId(String krwRequestResponseId) {
        this.krwRequestResponseId = krwRequestResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.member_idx
     *
     * @return the value of TA_KRW_REQUEST.member_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Integer getMemberIdx() {
        return memberIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.member_idx
     *
     * @param memberIdx the value for TA_KRW_REQUEST.member_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setMemberIdx(Integer memberIdx) {
        this.memberIdx = memberIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_KRW_REQUEST.member_id
     *
     * @return the value of TA_KRW_REQUEST.member_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_KRW_REQUEST.member_id
     *
     * @param memberId the value for TA_KRW_REQUEST.member_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }
}