package com.ints.common.model;

import java.util.Date;

public class TaMember {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_error
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberError;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_pass_hint
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberPassHint;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_name
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_nick
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberNick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_email
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_email_use
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberEmailUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_sms_use
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberSmsUse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_birth
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberBirth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_gender
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_address
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_home_phone
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberHomePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_cell_phone
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberCellPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_wallet
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberWallet;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_auth_status
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberAuthStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_auto_pay
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberAutoPay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_auto_pay_list
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberAutoPayList;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.reg_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.pass
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String pass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_krw
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberKrw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER.member_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberBtc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_idx
	 * @return  the value of TA_MEMBER.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_idx
	 * @param memberIdx  the value for TA_MEMBER.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberIdx(Integer memberIdx) {
		this.memberIdx = memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_error
	 * @return  the value of TA_MEMBER.member_error
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberError() {
		return memberError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_error
	 * @param memberError  the value for TA_MEMBER.member_error
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberError(String memberError) {
		this.memberError = memberError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_pass_hint
	 * @return  the value of TA_MEMBER.member_pass_hint
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberPassHint() {
		return memberPassHint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_pass_hint
	 * @param memberPassHint  the value for TA_MEMBER.member_pass_hint
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberPassHint(String memberPassHint) {
		this.memberPassHint = memberPassHint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_name
	 * @return  the value of TA_MEMBER.member_name
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberName() {
		return memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_name
	 * @param memberName  the value for TA_MEMBER.member_name
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_nick
	 * @return  the value of TA_MEMBER.member_nick
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberNick() {
		return memberNick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_nick
	 * @param memberNick  the value for TA_MEMBER.member_nick
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberNick(String memberNick) {
		this.memberNick = memberNick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_email
	 * @return  the value of TA_MEMBER.member_email
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberEmail() {
		return memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_email
	 * @param memberEmail  the value for TA_MEMBER.member_email
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberEmail(String memberEmail) {
		this.memberEmail = memberEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_email_use
	 * @return  the value of TA_MEMBER.member_email_use
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberEmailUse() {
		return memberEmailUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_email_use
	 * @param memberEmailUse  the value for TA_MEMBER.member_email_use
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberEmailUse(String memberEmailUse) {
		this.memberEmailUse = memberEmailUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_sms_use
	 * @return  the value of TA_MEMBER.member_sms_use
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberSmsUse() {
		return memberSmsUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_sms_use
	 * @param memberSmsUse  the value for TA_MEMBER.member_sms_use
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberSmsUse(String memberSmsUse) {
		this.memberSmsUse = memberSmsUse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_birth
	 * @return  the value of TA_MEMBER.member_birth
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberBirth() {
		return memberBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_birth
	 * @param memberBirth  the value for TA_MEMBER.member_birth
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberBirth(String memberBirth) {
		this.memberBirth = memberBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_gender
	 * @return  the value of TA_MEMBER.member_gender
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberGender() {
		return memberGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_gender
	 * @param memberGender  the value for TA_MEMBER.member_gender
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberGender(String memberGender) {
		this.memberGender = memberGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_address
	 * @return  the value of TA_MEMBER.member_address
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberAddress() {
		return memberAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_address
	 * @param memberAddress  the value for TA_MEMBER.member_address
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberAddress(String memberAddress) {
		this.memberAddress = memberAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_home_phone
	 * @return  the value of TA_MEMBER.member_home_phone
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberHomePhone() {
		return memberHomePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_home_phone
	 * @param memberHomePhone  the value for TA_MEMBER.member_home_phone
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberHomePhone(String memberHomePhone) {
		this.memberHomePhone = memberHomePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_cell_phone
	 * @return  the value of TA_MEMBER.member_cell_phone
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberCellPhone() {
		return memberCellPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_cell_phone
	 * @param memberCellPhone  the value for TA_MEMBER.member_cell_phone
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberCellPhone(String memberCellPhone) {
		this.memberCellPhone = memberCellPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_wallet
	 * @return  the value of TA_MEMBER.member_wallet
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberWallet() {
		return memberWallet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_wallet
	 * @param memberWallet  the value for TA_MEMBER.member_wallet
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWallet(String memberWallet) {
		this.memberWallet = memberWallet;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_auth_status
	 * @return  the value of TA_MEMBER.member_auth_status
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberAuthStatus() {
		return memberAuthStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_auth_status
	 * @param memberAuthStatus  the value for TA_MEMBER.member_auth_status
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberAuthStatus(String memberAuthStatus) {
		this.memberAuthStatus = memberAuthStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_auto_pay
	 * @return  the value of TA_MEMBER.member_auto_pay
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberAutoPay() {
		return memberAutoPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_auto_pay
	 * @param memberAutoPay  the value for TA_MEMBER.member_auto_pay
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberAutoPay(String memberAutoPay) {
		this.memberAutoPay = memberAutoPay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_auto_pay_list
	 * @return  the value of TA_MEMBER.member_auto_pay_list
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberAutoPayList() {
		return memberAutoPayList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_auto_pay_list
	 * @param memberAutoPayList  the value for TA_MEMBER.member_auto_pay_list
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberAutoPayList(String memberAutoPayList) {
		this.memberAutoPayList = memberAutoPayList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_id
	 * @return  the value of TA_MEMBER.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_id
	 * @param memberId  the value for TA_MEMBER.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.reg_date
	 * @return  the value of TA_MEMBER.reg_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.reg_date
	 * @param regDate  the value for TA_MEMBER.reg_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.pass
	 * @return  the value of TA_MEMBER.pass
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getPass() {
		return pass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.pass
	 * @param pass  the value for TA_MEMBER.pass
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setPass(String pass) {
		this.pass = pass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_krw
	 * @return  the value of TA_MEMBER.member_krw
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberKrw() {
		return memberKrw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_krw
	 * @param memberKrw  the value for TA_MEMBER.member_krw
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberKrw(Integer memberKrw) {
		this.memberKrw = memberKrw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER.member_btc
	 * @return  the value of TA_MEMBER.member_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberBtc() {
		return memberBtc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER.member_btc
	 * @param memberBtc  the value for TA_MEMBER.member_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberBtc(Integer memberBtc) {
		this.memberBtc = memberBtc;
	}
}