package com.ints.common.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class TaMemberExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public TaMemberExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMemberIdxIsNull() {
			addCriterion("member_idx is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIsNotNull() {
			addCriterion("member_idx is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdxEqualTo(Integer value) {
			addCriterion("member_idx =", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotEqualTo(Integer value) {
			addCriterion("member_idx <>", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxGreaterThan(Integer value) {
			addCriterion("member_idx >", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_idx >=", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxLessThan(Integer value) {
			addCriterion("member_idx <", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxLessThanOrEqualTo(Integer value) {
			addCriterion("member_idx <=", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIn(List<Integer> values) {
			addCriterion("member_idx in", values, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotIn(List<Integer> values) {
			addCriterion("member_idx not in", values, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxBetween(Integer value1, Integer value2) {
			addCriterion("member_idx between", value1, value2, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("member_idx not between", value1, value2, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberErrorIsNull() {
			addCriterion("member_error is null");
			return (Criteria) this;
		}

		public Criteria andMemberErrorIsNotNull() {
			addCriterion("member_error is not null");
			return (Criteria) this;
		}

		public Criteria andMemberErrorEqualTo(String value) {
			addCriterion("member_error =", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorNotEqualTo(String value) {
			addCriterion("member_error <>", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorGreaterThan(String value) {
			addCriterion("member_error >", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorGreaterThanOrEqualTo(String value) {
			addCriterion("member_error >=", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorLessThan(String value) {
			addCriterion("member_error <", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorLessThanOrEqualTo(String value) {
			addCriterion("member_error <=", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorLike(String value) {
			addCriterion("member_error like", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorNotLike(String value) {
			addCriterion("member_error not like", value, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorIn(List<String> values) {
			addCriterion("member_error in", values, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorNotIn(List<String> values) {
			addCriterion("member_error not in", values, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorBetween(String value1, String value2) {
			addCriterion("member_error between", value1, value2, "memberError");
			return (Criteria) this;
		}

		public Criteria andMemberErrorNotBetween(String value1, String value2) {
			addCriterion("member_error not between", value1, value2,
					"memberError");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintIsNull() {
			addCriterion("member_pass_hint is null");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintIsNotNull() {
			addCriterion("member_pass_hint is not null");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintEqualTo(String value) {
			addCriterion("member_pass_hint =", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintNotEqualTo(String value) {
			addCriterion("member_pass_hint <>", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintGreaterThan(String value) {
			addCriterion("member_pass_hint >", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintGreaterThanOrEqualTo(String value) {
			addCriterion("member_pass_hint >=", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintLessThan(String value) {
			addCriterion("member_pass_hint <", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintLessThanOrEqualTo(String value) {
			addCriterion("member_pass_hint <=", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintLike(String value) {
			addCriterion("member_pass_hint like", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintNotLike(String value) {
			addCriterion("member_pass_hint not like", value, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintIn(List<String> values) {
			addCriterion("member_pass_hint in", values, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintNotIn(List<String> values) {
			addCriterion("member_pass_hint not in", values, "memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintBetween(String value1, String value2) {
			addCriterion("member_pass_hint between", value1, value2,
					"memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberPassHintNotBetween(String value1, String value2) {
			addCriterion("member_pass_hint not between", value1, value2,
					"memberPassHint");
			return (Criteria) this;
		}

		public Criteria andMemberNameIsNull() {
			addCriterion("member_name is null");
			return (Criteria) this;
		}

		public Criteria andMemberNameIsNotNull() {
			addCriterion("member_name is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNameEqualTo(String value) {
			addCriterion("member_name =", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotEqualTo(String value) {
			addCriterion("member_name <>", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameGreaterThan(String value) {
			addCriterion("member_name >", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameGreaterThanOrEqualTo(String value) {
			addCriterion("member_name >=", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLessThan(String value) {
			addCriterion("member_name <", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLessThanOrEqualTo(String value) {
			addCriterion("member_name <=", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameLike(String value) {
			addCriterion("member_name like", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotLike(String value) {
			addCriterion("member_name not like", value, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameIn(List<String> values) {
			addCriterion("member_name in", values, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotIn(List<String> values) {
			addCriterion("member_name not in", values, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameBetween(String value1, String value2) {
			addCriterion("member_name between", value1, value2, "memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNameNotBetween(String value1, String value2) {
			addCriterion("member_name not between", value1, value2,
					"memberName");
			return (Criteria) this;
		}

		public Criteria andMemberNickIsNull() {
			addCriterion("member_nick is null");
			return (Criteria) this;
		}

		public Criteria andMemberNickIsNotNull() {
			addCriterion("member_nick is not null");
			return (Criteria) this;
		}

		public Criteria andMemberNickEqualTo(String value) {
			addCriterion("member_nick =", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickNotEqualTo(String value) {
			addCriterion("member_nick <>", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickGreaterThan(String value) {
			addCriterion("member_nick >", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickGreaterThanOrEqualTo(String value) {
			addCriterion("member_nick >=", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickLessThan(String value) {
			addCriterion("member_nick <", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickLessThanOrEqualTo(String value) {
			addCriterion("member_nick <=", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickLike(String value) {
			addCriterion("member_nick like", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickNotLike(String value) {
			addCriterion("member_nick not like", value, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickIn(List<String> values) {
			addCriterion("member_nick in", values, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickNotIn(List<String> values) {
			addCriterion("member_nick not in", values, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickBetween(String value1, String value2) {
			addCriterion("member_nick between", value1, value2, "memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberNickNotBetween(String value1, String value2) {
			addCriterion("member_nick not between", value1, value2,
					"memberNick");
			return (Criteria) this;
		}

		public Criteria andMemberEmailIsNull() {
			addCriterion("member_email is null");
			return (Criteria) this;
		}

		public Criteria andMemberEmailIsNotNull() {
			addCriterion("member_email is not null");
			return (Criteria) this;
		}

		public Criteria andMemberEmailEqualTo(String value) {
			addCriterion("member_email =", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotEqualTo(String value) {
			addCriterion("member_email <>", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailGreaterThan(String value) {
			addCriterion("member_email >", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailGreaterThanOrEqualTo(String value) {
			addCriterion("member_email >=", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailLessThan(String value) {
			addCriterion("member_email <", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailLessThanOrEqualTo(String value) {
			addCriterion("member_email <=", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailLike(String value) {
			addCriterion("member_email like", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotLike(String value) {
			addCriterion("member_email not like", value, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailIn(List<String> values) {
			addCriterion("member_email in", values, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotIn(List<String> values) {
			addCriterion("member_email not in", values, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailBetween(String value1, String value2) {
			addCriterion("member_email between", value1, value2, "memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailNotBetween(String value1, String value2) {
			addCriterion("member_email not between", value1, value2,
					"memberEmail");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseIsNull() {
			addCriterion("member_email_use is null");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseIsNotNull() {
			addCriterion("member_email_use is not null");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseEqualTo(String value) {
			addCriterion("member_email_use =", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseNotEqualTo(String value) {
			addCriterion("member_email_use <>", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseGreaterThan(String value) {
			addCriterion("member_email_use >", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseGreaterThanOrEqualTo(String value) {
			addCriterion("member_email_use >=", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseLessThan(String value) {
			addCriterion("member_email_use <", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseLessThanOrEqualTo(String value) {
			addCriterion("member_email_use <=", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseLike(String value) {
			addCriterion("member_email_use like", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseNotLike(String value) {
			addCriterion("member_email_use not like", value, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseIn(List<String> values) {
			addCriterion("member_email_use in", values, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseNotIn(List<String> values) {
			addCriterion("member_email_use not in", values, "memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseBetween(String value1, String value2) {
			addCriterion("member_email_use between", value1, value2,
					"memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberEmailUseNotBetween(String value1, String value2) {
			addCriterion("member_email_use not between", value1, value2,
					"memberEmailUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseIsNull() {
			addCriterion("member_sms_use is null");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseIsNotNull() {
			addCriterion("member_sms_use is not null");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseEqualTo(String value) {
			addCriterion("member_sms_use =", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseNotEqualTo(String value) {
			addCriterion("member_sms_use <>", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseGreaterThan(String value) {
			addCriterion("member_sms_use >", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseGreaterThanOrEqualTo(String value) {
			addCriterion("member_sms_use >=", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseLessThan(String value) {
			addCriterion("member_sms_use <", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseLessThanOrEqualTo(String value) {
			addCriterion("member_sms_use <=", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseLike(String value) {
			addCriterion("member_sms_use like", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseNotLike(String value) {
			addCriterion("member_sms_use not like", value, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseIn(List<String> values) {
			addCriterion("member_sms_use in", values, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseNotIn(List<String> values) {
			addCriterion("member_sms_use not in", values, "memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseBetween(String value1, String value2) {
			addCriterion("member_sms_use between", value1, value2,
					"memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberSmsUseNotBetween(String value1, String value2) {
			addCriterion("member_sms_use not between", value1, value2,
					"memberSmsUse");
			return (Criteria) this;
		}

		public Criteria andMemberBirthIsNull() {
			addCriterion("member_birth is null");
			return (Criteria) this;
		}

		public Criteria andMemberBirthIsNotNull() {
			addCriterion("member_birth is not null");
			return (Criteria) this;
		}

		public Criteria andMemberBirthEqualTo(String value) {
			addCriterion("member_birth =", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthNotEqualTo(String value) {
			addCriterion("member_birth <>", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthGreaterThan(String value) {
			addCriterion("member_birth >", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthGreaterThanOrEqualTo(String value) {
			addCriterion("member_birth >=", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthLessThan(String value) {
			addCriterion("member_birth <", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthLessThanOrEqualTo(String value) {
			addCriterion("member_birth <=", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthLike(String value) {
			addCriterion("member_birth like", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthNotLike(String value) {
			addCriterion("member_birth not like", value, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthIn(List<String> values) {
			addCriterion("member_birth in", values, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthNotIn(List<String> values) {
			addCriterion("member_birth not in", values, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthBetween(String value1, String value2) {
			addCriterion("member_birth between", value1, value2, "memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberBirthNotBetween(String value1, String value2) {
			addCriterion("member_birth not between", value1, value2,
					"memberBirth");
			return (Criteria) this;
		}

		public Criteria andMemberGenderIsNull() {
			addCriterion("member_gender is null");
			return (Criteria) this;
		}

		public Criteria andMemberGenderIsNotNull() {
			addCriterion("member_gender is not null");
			return (Criteria) this;
		}

		public Criteria andMemberGenderEqualTo(String value) {
			addCriterion("member_gender =", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderNotEqualTo(String value) {
			addCriterion("member_gender <>", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderGreaterThan(String value) {
			addCriterion("member_gender >", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderGreaterThanOrEqualTo(String value) {
			addCriterion("member_gender >=", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderLessThan(String value) {
			addCriterion("member_gender <", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderLessThanOrEqualTo(String value) {
			addCriterion("member_gender <=", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderLike(String value) {
			addCriterion("member_gender like", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderNotLike(String value) {
			addCriterion("member_gender not like", value, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderIn(List<String> values) {
			addCriterion("member_gender in", values, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderNotIn(List<String> values) {
			addCriterion("member_gender not in", values, "memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderBetween(String value1, String value2) {
			addCriterion("member_gender between", value1, value2,
					"memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberGenderNotBetween(String value1, String value2) {
			addCriterion("member_gender not between", value1, value2,
					"memberGender");
			return (Criteria) this;
		}

		public Criteria andMemberAddressIsNull() {
			addCriterion("member_address is null");
			return (Criteria) this;
		}

		public Criteria andMemberAddressIsNotNull() {
			addCriterion("member_address is not null");
			return (Criteria) this;
		}

		public Criteria andMemberAddressEqualTo(String value) {
			addCriterion("member_address =", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressNotEqualTo(String value) {
			addCriterion("member_address <>", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressGreaterThan(String value) {
			addCriterion("member_address >", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressGreaterThanOrEqualTo(String value) {
			addCriterion("member_address >=", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressLessThan(String value) {
			addCriterion("member_address <", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressLessThanOrEqualTo(String value) {
			addCriterion("member_address <=", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressLike(String value) {
			addCriterion("member_address like", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressNotLike(String value) {
			addCriterion("member_address not like", value, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressIn(List<String> values) {
			addCriterion("member_address in", values, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressNotIn(List<String> values) {
			addCriterion("member_address not in", values, "memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressBetween(String value1, String value2) {
			addCriterion("member_address between", value1, value2,
					"memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberAddressNotBetween(String value1, String value2) {
			addCriterion("member_address not between", value1, value2,
					"memberAddress");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneIsNull() {
			addCriterion("member_home_phone is null");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneIsNotNull() {
			addCriterion("member_home_phone is not null");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneEqualTo(String value) {
			addCriterion("member_home_phone =", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneNotEqualTo(String value) {
			addCriterion("member_home_phone <>", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneGreaterThan(String value) {
			addCriterion("member_home_phone >", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("member_home_phone >=", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneLessThan(String value) {
			addCriterion("member_home_phone <", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneLessThanOrEqualTo(String value) {
			addCriterion("member_home_phone <=", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneLike(String value) {
			addCriterion("member_home_phone like", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneNotLike(String value) {
			addCriterion("member_home_phone not like", value, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneIn(List<String> values) {
			addCriterion("member_home_phone in", values, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneNotIn(List<String> values) {
			addCriterion("member_home_phone not in", values, "memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneBetween(String value1, String value2) {
			addCriterion("member_home_phone between", value1, value2,
					"memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberHomePhoneNotBetween(String value1,
				String value2) {
			addCriterion("member_home_phone not between", value1, value2,
					"memberHomePhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneIsNull() {
			addCriterion("member_cell_phone is null");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneIsNotNull() {
			addCriterion("member_cell_phone is not null");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneEqualTo(String value) {
			addCriterion("member_cell_phone =", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneNotEqualTo(String value) {
			addCriterion("member_cell_phone <>", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneGreaterThan(String value) {
			addCriterion("member_cell_phone >", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("member_cell_phone >=", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneLessThan(String value) {
			addCriterion("member_cell_phone <", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneLessThanOrEqualTo(String value) {
			addCriterion("member_cell_phone <=", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneLike(String value) {
			addCriterion("member_cell_phone like", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneNotLike(String value) {
			addCriterion("member_cell_phone not like", value, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneIn(List<String> values) {
			addCriterion("member_cell_phone in", values, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneNotIn(List<String> values) {
			addCriterion("member_cell_phone not in", values, "memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneBetween(String value1, String value2) {
			addCriterion("member_cell_phone between", value1, value2,
					"memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberCellPhoneNotBetween(String value1,
				String value2) {
			addCriterion("member_cell_phone not between", value1, value2,
					"memberCellPhone");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIsNull() {
			addCriterion("member_wallet is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIsNotNull() {
			addCriterion("member_wallet is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletEqualTo(String value) {
			addCriterion("member_wallet =", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletNotEqualTo(String value) {
			addCriterion("member_wallet <>", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletGreaterThan(String value) {
			addCriterion("member_wallet >", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletGreaterThanOrEqualTo(String value) {
			addCriterion("member_wallet >=", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletLessThan(String value) {
			addCriterion("member_wallet <", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletLessThanOrEqualTo(String value) {
			addCriterion("member_wallet <=", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletLike(String value) {
			addCriterion("member_wallet like", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletNotLike(String value) {
			addCriterion("member_wallet not like", value, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIn(List<String> values) {
			addCriterion("member_wallet in", values, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletNotIn(List<String> values) {
			addCriterion("member_wallet not in", values, "memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBetween(String value1, String value2) {
			addCriterion("member_wallet between", value1, value2,
					"memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberWalletNotBetween(String value1, String value2) {
			addCriterion("member_wallet not between", value1, value2,
					"memberWallet");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusIsNull() {
			addCriterion("member_auth_status is null");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusIsNotNull() {
			addCriterion("member_auth_status is not null");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusEqualTo(String value) {
			addCriterion("member_auth_status =", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusNotEqualTo(String value) {
			addCriterion("member_auth_status <>", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusGreaterThan(String value) {
			addCriterion("member_auth_status >", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusGreaterThanOrEqualTo(String value) {
			addCriterion("member_auth_status >=", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusLessThan(String value) {
			addCriterion("member_auth_status <", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusLessThanOrEqualTo(String value) {
			addCriterion("member_auth_status <=", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusLike(String value) {
			addCriterion("member_auth_status like", value, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusNotLike(String value) {
			addCriterion("member_auth_status not like", value,
					"memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusIn(List<String> values) {
			addCriterion("member_auth_status in", values, "memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusNotIn(List<String> values) {
			addCriterion("member_auth_status not in", values,
					"memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusBetween(String value1, String value2) {
			addCriterion("member_auth_status between", value1, value2,
					"memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAuthStatusNotBetween(String value1,
				String value2) {
			addCriterion("member_auth_status not between", value1, value2,
					"memberAuthStatus");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayIsNull() {
			addCriterion("member_auto_pay is null");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayIsNotNull() {
			addCriterion("member_auto_pay is not null");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayEqualTo(String value) {
			addCriterion("member_auto_pay =", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayNotEqualTo(String value) {
			addCriterion("member_auto_pay <>", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayGreaterThan(String value) {
			addCriterion("member_auto_pay >", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayGreaterThanOrEqualTo(String value) {
			addCriterion("member_auto_pay >=", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayLessThan(String value) {
			addCriterion("member_auto_pay <", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayLessThanOrEqualTo(String value) {
			addCriterion("member_auto_pay <=", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayLike(String value) {
			addCriterion("member_auto_pay like", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayNotLike(String value) {
			addCriterion("member_auto_pay not like", value, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayIn(List<String> values) {
			addCriterion("member_auto_pay in", values, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayNotIn(List<String> values) {
			addCriterion("member_auto_pay not in", values, "memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayBetween(String value1, String value2) {
			addCriterion("member_auto_pay between", value1, value2,
					"memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayNotBetween(String value1, String value2) {
			addCriterion("member_auto_pay not between", value1, value2,
					"memberAutoPay");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListIsNull() {
			addCriterion("member_auto_pay_list is null");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListIsNotNull() {
			addCriterion("member_auto_pay_list is not null");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListEqualTo(String value) {
			addCriterion("member_auto_pay_list =", value, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListNotEqualTo(String value) {
			addCriterion("member_auto_pay_list <>", value, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListGreaterThan(String value) {
			addCriterion("member_auto_pay_list >", value, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListGreaterThanOrEqualTo(String value) {
			addCriterion("member_auto_pay_list >=", value, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListLessThan(String value) {
			addCriterion("member_auto_pay_list <", value, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListLessThanOrEqualTo(String value) {
			addCriterion("member_auto_pay_list <=", value, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListLike(String value) {
			addCriterion("member_auto_pay_list like", value,
					"memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListNotLike(String value) {
			addCriterion("member_auto_pay_list not like", value,
					"memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListIn(List<String> values) {
			addCriterion("member_auto_pay_list in", values, "memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListNotIn(List<String> values) {
			addCriterion("member_auto_pay_list not in", values,
					"memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListBetween(String value1, String value2) {
			addCriterion("member_auto_pay_list between", value1, value2,
					"memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberAutoPayListNotBetween(String value1,
				String value2) {
			addCriterion("member_auto_pay_list not between", value1, value2,
					"memberAutoPayList");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("member_id is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("member_id is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdEqualTo(String value) {
			addCriterion("member_id =", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotEqualTo(String value) {
			addCriterion("member_id <>", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThan(String value) {
			addCriterion("member_id >", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("member_id >=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThan(String value) {
			addCriterion("member_id <", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(String value) {
			addCriterion("member_id <=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLike(String value) {
			addCriterion("member_id like", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotLike(String value) {
			addCriterion("member_id not like", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIn(List<String> values) {
			addCriterion("member_id in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotIn(List<String> values) {
			addCriterion("member_id not in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdBetween(String value1, String value2) {
			addCriterion("member_id between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotBetween(String value1, String value2) {
			addCriterion("member_id not between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNull() {
			addCriterion("reg_date is null");
			return (Criteria) this;
		}

		public Criteria andRegDateIsNotNull() {
			addCriterion("reg_date is not null");
			return (Criteria) this;
		}

		public Criteria andRegDateEqualTo(Date value) {
			addCriterion("reg_date =", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotEqualTo(Date value) {
			addCriterion("reg_date <>", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThan(Date value) {
			addCriterion("reg_date >", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateGreaterThanOrEqualTo(Date value) {
			addCriterion("reg_date >=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThan(Date value) {
			addCriterion("reg_date <", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateLessThanOrEqualTo(Date value) {
			addCriterion("reg_date <=", value, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateIn(List<Date> values) {
			addCriterion("reg_date in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotIn(List<Date> values) {
			addCriterion("reg_date not in", values, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateBetween(Date value1, Date value2) {
			addCriterion("reg_date between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andRegDateNotBetween(Date value1, Date value2) {
			addCriterion("reg_date not between", value1, value2, "regDate");
			return (Criteria) this;
		}

		public Criteria andPassIsNull() {
			addCriterion("pass is null");
			return (Criteria) this;
		}

		public Criteria andPassIsNotNull() {
			addCriterion("pass is not null");
			return (Criteria) this;
		}

		public Criteria andPassEqualTo(String value) {
			addCriterion("pass =", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassNotEqualTo(String value) {
			addCriterion("pass <>", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassGreaterThan(String value) {
			addCriterion("pass >", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassGreaterThanOrEqualTo(String value) {
			addCriterion("pass >=", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassLessThan(String value) {
			addCriterion("pass <", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassLessThanOrEqualTo(String value) {
			addCriterion("pass <=", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassLike(String value) {
			addCriterion("pass like", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassNotLike(String value) {
			addCriterion("pass not like", value, "pass");
			return (Criteria) this;
		}

		public Criteria andPassIn(List<String> values) {
			addCriterion("pass in", values, "pass");
			return (Criteria) this;
		}

		public Criteria andPassNotIn(List<String> values) {
			addCriterion("pass not in", values, "pass");
			return (Criteria) this;
		}

		public Criteria andPassBetween(String value1, String value2) {
			addCriterion("pass between", value1, value2, "pass");
			return (Criteria) this;
		}

		public Criteria andPassNotBetween(String value1, String value2) {
			addCriterion("pass not between", value1, value2, "pass");
			return (Criteria) this;
		}

		public Criteria andMemberKrwIsNull() {
			addCriterion("member_krw is null");
			return (Criteria) this;
		}

		public Criteria andMemberKrwIsNotNull() {
			addCriterion("member_krw is not null");
			return (Criteria) this;
		}

		public Criteria andMemberKrwEqualTo(Integer value) {
			addCriterion("member_krw =", value, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwNotEqualTo(Integer value) {
			addCriterion("member_krw <>", value, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwGreaterThan(Integer value) {
			addCriterion("member_krw >", value, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_krw >=", value, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwLessThan(Integer value) {
			addCriterion("member_krw <", value, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwLessThanOrEqualTo(Integer value) {
			addCriterion("member_krw <=", value, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwIn(List<Integer> values) {
			addCriterion("member_krw in", values, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwNotIn(List<Integer> values) {
			addCriterion("member_krw not in", values, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwBetween(Integer value1, Integer value2) {
			addCriterion("member_krw between", value1, value2, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberKrwNotBetween(Integer value1, Integer value2) {
			addCriterion("member_krw not between", value1, value2, "memberKrw");
			return (Criteria) this;
		}

		public Criteria andMemberBtcIsNull() {
			addCriterion("member_btc is null");
			return (Criteria) this;
		}

		public Criteria andMemberBtcIsNotNull() {
			addCriterion("member_btc is not null");
			return (Criteria) this;
		}

		public Criteria andMemberBtcEqualTo(Integer value) {
			addCriterion("member_btc =", value, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcNotEqualTo(Integer value) {
			addCriterion("member_btc <>", value, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcGreaterThan(Integer value) {
			addCriterion("member_btc >", value, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_btc >=", value, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcLessThan(Integer value) {
			addCriterion("member_btc <", value, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcLessThanOrEqualTo(Integer value) {
			addCriterion("member_btc <=", value, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcIn(List<Integer> values) {
			addCriterion("member_btc in", values, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcNotIn(List<Integer> values) {
			addCriterion("member_btc not in", values, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcBetween(Integer value1, Integer value2) {
			addCriterion("member_btc between", value1, value2, "memberBtc");
			return (Criteria) this;
		}

		public Criteria andMemberBtcNotBetween(Integer value1, Integer value2) {
			addCriterion("member_btc not between", value1, value2, "memberBtc");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_MEMBER
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_MEMBER
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 23 17:53:05 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}