package com.ints.common.model;

import java.util.Date;

public class TaMemberWallet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberWalletIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_type
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberWalletType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_seller
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberWalletSeller;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberWalletBtc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_krw
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberWalletKrw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_datetime
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date memberWalletDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.txid
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String txid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.btc_address
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String btcAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_MEMBER_WALLET.member_wallet_seller_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberWalletSellerIdx;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_idx
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberWalletIdx() {
		return memberWalletIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_idx
	 * @param memberWalletIdx  the value for TA_MEMBER_WALLET.member_wallet_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletIdx(Integer memberWalletIdx) {
		this.memberWalletIdx = memberWalletIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_type
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_type
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberWalletType() {
		return memberWalletType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_type
	 * @param memberWalletType  the value for TA_MEMBER_WALLET.member_wallet_type
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletType(String memberWalletType) {
		this.memberWalletType = memberWalletType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_seller
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_seller
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberWalletSeller() {
		return memberWalletSeller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_seller
	 * @param memberWalletSeller  the value for TA_MEMBER_WALLET.member_wallet_seller
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletSeller(String memberWalletSeller) {
		this.memberWalletSeller = memberWalletSeller;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_btc
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberWalletBtc() {
		return memberWalletBtc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_btc
	 * @param memberWalletBtc  the value for TA_MEMBER_WALLET.member_wallet_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletBtc(Integer memberWalletBtc) {
		this.memberWalletBtc = memberWalletBtc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_krw
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_krw
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberWalletKrw() {
		return memberWalletKrw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_krw
	 * @param memberWalletKrw  the value for TA_MEMBER_WALLET.member_wallet_krw
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletKrw(Integer memberWalletKrw) {
		this.memberWalletKrw = memberWalletKrw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_datetime
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_datetime
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getMemberWalletDatetime() {
		return memberWalletDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_datetime
	 * @param memberWalletDatetime  the value for TA_MEMBER_WALLET.member_wallet_datetime
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletDatetime(Date memberWalletDatetime) {
		this.memberWalletDatetime = memberWalletDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.txid
	 * @return  the value of TA_MEMBER_WALLET.txid
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getTxid() {
		return txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.txid
	 * @param txid  the value for TA_MEMBER_WALLET.txid
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setTxid(String txid) {
		this.txid = txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.btc_address
	 * @return  the value of TA_MEMBER_WALLET.btc_address
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getBtcAddress() {
		return btcAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.btc_address
	 * @param btcAddress  the value for TA_MEMBER_WALLET.btc_address
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setBtcAddress(String btcAddress) {
		this.btcAddress = btcAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_idx
	 * @return  the value of TA_MEMBER_WALLET.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_idx
	 * @param memberIdx  the value for TA_MEMBER_WALLET.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberIdx(Integer memberIdx) {
		this.memberIdx = memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_id
	 * @return  the value of TA_MEMBER_WALLET.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_id
	 * @param memberId  the value for TA_MEMBER_WALLET.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_MEMBER_WALLET.member_wallet_seller_idx
	 * @return  the value of TA_MEMBER_WALLET.member_wallet_seller_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberWalletSellerIdx() {
		return memberWalletSellerIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_MEMBER_WALLET.member_wallet_seller_idx
	 * @param memberWalletSellerIdx  the value for TA_MEMBER_WALLET.member_wallet_seller_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberWalletSellerIdx(Integer memberWalletSellerIdx) {
		this.memberWalletSellerIdx = memberWalletSellerIdx;
	}
}