package com.ints.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaMemberWalletExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public TaMemberWalletExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMemberWalletIdxIsNull() {
			addCriterion("member_wallet_idx is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxIsNotNull() {
			addCriterion("member_wallet_idx is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxEqualTo(Integer value) {
			addCriterion("member_wallet_idx =", value, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxNotEqualTo(Integer value) {
			addCriterion("member_wallet_idx <>", value, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxGreaterThan(Integer value) {
			addCriterion("member_wallet_idx >", value, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_idx >=", value, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxLessThan(Integer value) {
			addCriterion("member_wallet_idx <", value, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxLessThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_idx <=", value, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxIn(List<Integer> values) {
			addCriterion("member_wallet_idx in", values, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxNotIn(List<Integer> values) {
			addCriterion("member_wallet_idx not in", values, "memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxBetween(Integer value1, Integer value2) {
			addCriterion("member_wallet_idx between", value1, value2,
					"memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletIdxNotBetween(Integer value1,
				Integer value2) {
			addCriterion("member_wallet_idx not between", value1, value2,
					"memberWalletIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeIsNull() {
			addCriterion("member_wallet_type is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeIsNotNull() {
			addCriterion("member_wallet_type is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeEqualTo(String value) {
			addCriterion("member_wallet_type =", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeNotEqualTo(String value) {
			addCriterion("member_wallet_type <>", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeGreaterThan(String value) {
			addCriterion("member_wallet_type >", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeGreaterThanOrEqualTo(String value) {
			addCriterion("member_wallet_type >=", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeLessThan(String value) {
			addCriterion("member_wallet_type <", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeLessThanOrEqualTo(String value) {
			addCriterion("member_wallet_type <=", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeLike(String value) {
			addCriterion("member_wallet_type like", value, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeNotLike(String value) {
			addCriterion("member_wallet_type not like", value,
					"memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeIn(List<String> values) {
			addCriterion("member_wallet_type in", values, "memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeNotIn(List<String> values) {
			addCriterion("member_wallet_type not in", values,
					"memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeBetween(String value1, String value2) {
			addCriterion("member_wallet_type between", value1, value2,
					"memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletTypeNotBetween(String value1,
				String value2) {
			addCriterion("member_wallet_type not between", value1, value2,
					"memberWalletType");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIsNull() {
			addCriterion("member_wallet_seller is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIsNotNull() {
			addCriterion("member_wallet_seller is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerEqualTo(String value) {
			addCriterion("member_wallet_seller =", value, "memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerNotEqualTo(String value) {
			addCriterion("member_wallet_seller <>", value, "memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerGreaterThan(String value) {
			addCriterion("member_wallet_seller >", value, "memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerGreaterThanOrEqualTo(String value) {
			addCriterion("member_wallet_seller >=", value, "memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerLessThan(String value) {
			addCriterion("member_wallet_seller <", value, "memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerLessThanOrEqualTo(String value) {
			addCriterion("member_wallet_seller <=", value, "memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerLike(String value) {
			addCriterion("member_wallet_seller like", value,
					"memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerNotLike(String value) {
			addCriterion("member_wallet_seller not like", value,
					"memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIn(List<String> values) {
			addCriterion("member_wallet_seller in", values,
					"memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerNotIn(List<String> values) {
			addCriterion("member_wallet_seller not in", values,
					"memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerBetween(String value1,
				String value2) {
			addCriterion("member_wallet_seller between", value1, value2,
					"memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerNotBetween(String value1,
				String value2) {
			addCriterion("member_wallet_seller not between", value1, value2,
					"memberWalletSeller");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcIsNull() {
			addCriterion("member_wallet_btc is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcIsNotNull() {
			addCriterion("member_wallet_btc is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcEqualTo(Integer value) {
			addCriterion("member_wallet_btc =", value, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcNotEqualTo(Integer value) {
			addCriterion("member_wallet_btc <>", value, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcGreaterThan(Integer value) {
			addCriterion("member_wallet_btc >", value, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_btc >=", value, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcLessThan(Integer value) {
			addCriterion("member_wallet_btc <", value, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcLessThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_btc <=", value, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcIn(List<Integer> values) {
			addCriterion("member_wallet_btc in", values, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcNotIn(List<Integer> values) {
			addCriterion("member_wallet_btc not in", values, "memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcBetween(Integer value1, Integer value2) {
			addCriterion("member_wallet_btc between", value1, value2,
					"memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletBtcNotBetween(Integer value1,
				Integer value2) {
			addCriterion("member_wallet_btc not between", value1, value2,
					"memberWalletBtc");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwIsNull() {
			addCriterion("member_wallet_krw is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwIsNotNull() {
			addCriterion("member_wallet_krw is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwEqualTo(Integer value) {
			addCriterion("member_wallet_krw =", value, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwNotEqualTo(Integer value) {
			addCriterion("member_wallet_krw <>", value, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwGreaterThan(Integer value) {
			addCriterion("member_wallet_krw >", value, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_krw >=", value, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwLessThan(Integer value) {
			addCriterion("member_wallet_krw <", value, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwLessThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_krw <=", value, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwIn(List<Integer> values) {
			addCriterion("member_wallet_krw in", values, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwNotIn(List<Integer> values) {
			addCriterion("member_wallet_krw not in", values, "memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwBetween(Integer value1, Integer value2) {
			addCriterion("member_wallet_krw between", value1, value2,
					"memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletKrwNotBetween(Integer value1,
				Integer value2) {
			addCriterion("member_wallet_krw not between", value1, value2,
					"memberWalletKrw");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeIsNull() {
			addCriterion("member_wallet_datetime is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeIsNotNull() {
			addCriterion("member_wallet_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeEqualTo(Date value) {
			addCriterion("member_wallet_datetime =", value,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeNotEqualTo(Date value) {
			addCriterion("member_wallet_datetime <>", value,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeGreaterThan(Date value) {
			addCriterion("member_wallet_datetime >", value,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("member_wallet_datetime >=", value,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeLessThan(Date value) {
			addCriterion("member_wallet_datetime <", value,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("member_wallet_datetime <=", value,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeIn(List<Date> values) {
			addCriterion("member_wallet_datetime in", values,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeNotIn(List<Date> values) {
			addCriterion("member_wallet_datetime not in", values,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeBetween(Date value1, Date value2) {
			addCriterion("member_wallet_datetime between", value1, value2,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andMemberWalletDatetimeNotBetween(Date value1,
				Date value2) {
			addCriterion("member_wallet_datetime not between", value1, value2,
					"memberWalletDatetime");
			return (Criteria) this;
		}

		public Criteria andTxidIsNull() {
			addCriterion("txid is null");
			return (Criteria) this;
		}

		public Criteria andTxidIsNotNull() {
			addCriterion("txid is not null");
			return (Criteria) this;
		}

		public Criteria andTxidEqualTo(String value) {
			addCriterion("txid =", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotEqualTo(String value) {
			addCriterion("txid <>", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidGreaterThan(String value) {
			addCriterion("txid >", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidGreaterThanOrEqualTo(String value) {
			addCriterion("txid >=", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidLessThan(String value) {
			addCriterion("txid <", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidLessThanOrEqualTo(String value) {
			addCriterion("txid <=", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidLike(String value) {
			addCriterion("txid like", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotLike(String value) {
			addCriterion("txid not like", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidIn(List<String> values) {
			addCriterion("txid in", values, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotIn(List<String> values) {
			addCriterion("txid not in", values, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidBetween(String value1, String value2) {
			addCriterion("txid between", value1, value2, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotBetween(String value1, String value2) {
			addCriterion("txid not between", value1, value2, "txid");
			return (Criteria) this;
		}

		public Criteria andBtcAddressIsNull() {
			addCriterion("btc_address is null");
			return (Criteria) this;
		}

		public Criteria andBtcAddressIsNotNull() {
			addCriterion("btc_address is not null");
			return (Criteria) this;
		}

		public Criteria andBtcAddressEqualTo(String value) {
			addCriterion("btc_address =", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressNotEqualTo(String value) {
			addCriterion("btc_address <>", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressGreaterThan(String value) {
			addCriterion("btc_address >", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressGreaterThanOrEqualTo(String value) {
			addCriterion("btc_address >=", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressLessThan(String value) {
			addCriterion("btc_address <", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressLessThanOrEqualTo(String value) {
			addCriterion("btc_address <=", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressLike(String value) {
			addCriterion("btc_address like", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressNotLike(String value) {
			addCriterion("btc_address not like", value, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressIn(List<String> values) {
			addCriterion("btc_address in", values, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressNotIn(List<String> values) {
			addCriterion("btc_address not in", values, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressBetween(String value1, String value2) {
			addCriterion("btc_address between", value1, value2, "btcAddress");
			return (Criteria) this;
		}

		public Criteria andBtcAddressNotBetween(String value1, String value2) {
			addCriterion("btc_address not between", value1, value2,
					"btcAddress");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIsNull() {
			addCriterion("member_idx is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIsNotNull() {
			addCriterion("member_idx is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdxEqualTo(Integer value) {
			addCriterion("member_idx =", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotEqualTo(Integer value) {
			addCriterion("member_idx <>", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxGreaterThan(Integer value) {
			addCriterion("member_idx >", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_idx >=", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxLessThan(Integer value) {
			addCriterion("member_idx <", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxLessThanOrEqualTo(Integer value) {
			addCriterion("member_idx <=", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIn(List<Integer> values) {
			addCriterion("member_idx in", values, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotIn(List<Integer> values) {
			addCriterion("member_idx not in", values, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxBetween(Integer value1, Integer value2) {
			addCriterion("member_idx between", value1, value2, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("member_idx not between", value1, value2, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("member_id is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("member_id is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdEqualTo(String value) {
			addCriterion("member_id =", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotEqualTo(String value) {
			addCriterion("member_id <>", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThan(String value) {
			addCriterion("member_id >", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("member_id >=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThan(String value) {
			addCriterion("member_id <", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(String value) {
			addCriterion("member_id <=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLike(String value) {
			addCriterion("member_id like", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotLike(String value) {
			addCriterion("member_id not like", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIn(List<String> values) {
			addCriterion("member_id in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotIn(List<String> values) {
			addCriterion("member_id not in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdBetween(String value1, String value2) {
			addCriterion("member_id between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotBetween(String value1, String value2) {
			addCriterion("member_id not between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxIsNull() {
			addCriterion("member_wallet_seller_idx is null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxIsNotNull() {
			addCriterion("member_wallet_seller_idx is not null");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxEqualTo(Integer value) {
			addCriterion("member_wallet_seller_idx =", value,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxNotEqualTo(Integer value) {
			addCriterion("member_wallet_seller_idx <>", value,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxGreaterThan(Integer value) {
			addCriterion("member_wallet_seller_idx >", value,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxGreaterThanOrEqualTo(
				Integer value) {
			addCriterion("member_wallet_seller_idx >=", value,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxLessThan(Integer value) {
			addCriterion("member_wallet_seller_idx <", value,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxLessThanOrEqualTo(Integer value) {
			addCriterion("member_wallet_seller_idx <=", value,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxIn(List<Integer> values) {
			addCriterion("member_wallet_seller_idx in", values,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxNotIn(List<Integer> values) {
			addCriterion("member_wallet_seller_idx not in", values,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxBetween(Integer value1,
				Integer value2) {
			addCriterion("member_wallet_seller_idx between", value1, value2,
					"memberWalletSellerIdx");
			return (Criteria) this;
		}

		public Criteria andMemberWalletSellerIdxNotBetween(Integer value1,
				Integer value2) {
			addCriterion("member_wallet_seller_idx not between", value1,
					value2, "memberWalletSellerIdx");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_MEMBER_WALLET
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 23 17:53:05 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}