package com.ints.common.model;

import java.util.Date;

public class TaPopupMng {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.popup_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer popupMngIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.subject
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.win_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String winDatePop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.use_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer useIs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.start_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String startDatePop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.thumb
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String thumb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.event_page_exlink
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String eventPageExlink;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.end_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String endDatePop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.hitcount
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer hitcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.attatch_file
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String attatchFile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.start_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String startDateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.end_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String endDateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.win_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String winDateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_POPUP_MNG.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.popup_mng_idx
	 * @return  the value of TA_POPUP_MNG.popup_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getPopupMngIdx() {
		return popupMngIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.popup_mng_idx
	 * @param popupMngIdx  the value for TA_POPUP_MNG.popup_mng_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setPopupMngIdx(Integer popupMngIdx) {
		this.popupMngIdx = popupMngIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.subject
	 * @return  the value of TA_POPUP_MNG.subject
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.subject
	 * @param subject  the value for TA_POPUP_MNG.subject
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.win_date_pop
	 * @return  the value of TA_POPUP_MNG.win_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getWinDatePop() {
		return winDatePop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.win_date_pop
	 * @param winDatePop  the value for TA_POPUP_MNG.win_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setWinDatePop(String winDatePop) {
		this.winDatePop = winDatePop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.use_is
	 * @return  the value of TA_POPUP_MNG.use_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getUseIs() {
		return useIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.use_is
	 * @param useIs  the value for TA_POPUP_MNG.use_is
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setUseIs(Integer useIs) {
		this.useIs = useIs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.start_date_pop
	 * @return  the value of TA_POPUP_MNG.start_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getStartDatePop() {
		return startDatePop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.start_date_pop
	 * @param startDatePop  the value for TA_POPUP_MNG.start_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setStartDatePop(String startDatePop) {
		this.startDatePop = startDatePop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.thumb
	 * @return  the value of TA_POPUP_MNG.thumb
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getThumb() {
		return thumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.thumb
	 * @param thumb  the value for TA_POPUP_MNG.thumb
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setThumb(String thumb) {
		this.thumb = thumb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.event_page_exlink
	 * @return  the value of TA_POPUP_MNG.event_page_exlink
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getEventPageExlink() {
		return eventPageExlink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.event_page_exlink
	 * @param eventPageExlink  the value for TA_POPUP_MNG.event_page_exlink
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setEventPageExlink(String eventPageExlink) {
		this.eventPageExlink = eventPageExlink;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.end_date_pop
	 * @return  the value of TA_POPUP_MNG.end_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getEndDatePop() {
		return endDatePop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.end_date_pop
	 * @param endDatePop  the value for TA_POPUP_MNG.end_date_pop
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setEndDatePop(String endDatePop) {
		this.endDatePop = endDatePop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.create_id
	 * @return  the value of TA_POPUP_MNG.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.create_id
	 * @param createId  the value for TA_POPUP_MNG.create_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setCreateId(String createId) {
		this.createId = createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.create_date
	 * @return  the value of TA_POPUP_MNG.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.create_date
	 * @param createDate  the value for TA_POPUP_MNG.create_date
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.hitcount
	 * @return  the value of TA_POPUP_MNG.hitcount
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getHitcount() {
		return hitcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.hitcount
	 * @param hitcount  the value for TA_POPUP_MNG.hitcount
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setHitcount(Integer hitcount) {
		this.hitcount = hitcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.attatch_file
	 * @return  the value of TA_POPUP_MNG.attatch_file
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getAttatchFile() {
		return attatchFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.attatch_file
	 * @param attatchFile  the value for TA_POPUP_MNG.attatch_file
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setAttatchFile(String attatchFile) {
		this.attatchFile = attatchFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.start_date_time
	 * @return  the value of TA_POPUP_MNG.start_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getStartDateTime() {
		return startDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.start_date_time
	 * @param startDateTime  the value for TA_POPUP_MNG.start_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setStartDateTime(String startDateTime) {
		this.startDateTime = startDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.end_date_time
	 * @return  the value of TA_POPUP_MNG.end_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getEndDateTime() {
		return endDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.end_date_time
	 * @param endDateTime  the value for TA_POPUP_MNG.end_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setEndDateTime(String endDateTime) {
		this.endDateTime = endDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.win_date_time
	 * @return  the value of TA_POPUP_MNG.win_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getWinDateTime() {
		return winDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.win_date_time
	 * @param winDateTime  the value for TA_POPUP_MNG.win_date_time
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setWinDateTime(String winDateTime) {
		this.winDateTime = winDateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_POPUP_MNG.content
	 * @return  the value of TA_POPUP_MNG.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_POPUP_MNG.content
	 * @param content  the value for TA_POPUP_MNG.content
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setContent(String content) {
		this.content = content;
	}
}