package com.ints.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaRealbtcExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public TaRealbtcExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRealbtcIdxIsNull() {
			addCriterion("realbtc_idx is null");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxIsNotNull() {
			addCriterion("realbtc_idx is not null");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxEqualTo(Integer value) {
			addCriterion("realbtc_idx =", value, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxNotEqualTo(Integer value) {
			addCriterion("realbtc_idx <>", value, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxGreaterThan(Integer value) {
			addCriterion("realbtc_idx >", value, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("realbtc_idx >=", value, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxLessThan(Integer value) {
			addCriterion("realbtc_idx <", value, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxLessThanOrEqualTo(Integer value) {
			addCriterion("realbtc_idx <=", value, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxIn(List<Integer> values) {
			addCriterion("realbtc_idx in", values, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxNotIn(List<Integer> values) {
			addCriterion("realbtc_idx not in", values, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxBetween(Integer value1, Integer value2) {
			addCriterion("realbtc_idx between", value1, value2, "realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("realbtc_idx not between", value1, value2,
					"realbtcIdx");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeIsNull() {
			addCriterion("realbtc_type is null");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeIsNotNull() {
			addCriterion("realbtc_type is not null");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeEqualTo(String value) {
			addCriterion("realbtc_type =", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeNotEqualTo(String value) {
			addCriterion("realbtc_type <>", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeGreaterThan(String value) {
			addCriterion("realbtc_type >", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeGreaterThanOrEqualTo(String value) {
			addCriterion("realbtc_type >=", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeLessThan(String value) {
			addCriterion("realbtc_type <", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeLessThanOrEqualTo(String value) {
			addCriterion("realbtc_type <=", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeLike(String value) {
			addCriterion("realbtc_type like", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeNotLike(String value) {
			addCriterion("realbtc_type not like", value, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeIn(List<String> values) {
			addCriterion("realbtc_type in", values, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeNotIn(List<String> values) {
			addCriterion("realbtc_type not in", values, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeBetween(String value1, String value2) {
			addCriterion("realbtc_type between", value1, value2, "realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcTypeNotBetween(String value1, String value2) {
			addCriterion("realbtc_type not between", value1, value2,
					"realbtcType");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcIsNull() {
			addCriterion("realbtc_btc is null");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcIsNotNull() {
			addCriterion("realbtc_btc is not null");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcEqualTo(Integer value) {
			addCriterion("realbtc_btc =", value, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcNotEqualTo(Integer value) {
			addCriterion("realbtc_btc <>", value, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcGreaterThan(Integer value) {
			addCriterion("realbtc_btc >", value, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcGreaterThanOrEqualTo(Integer value) {
			addCriterion("realbtc_btc >=", value, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcLessThan(Integer value) {
			addCriterion("realbtc_btc <", value, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcLessThanOrEqualTo(Integer value) {
			addCriterion("realbtc_btc <=", value, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcIn(List<Integer> values) {
			addCriterion("realbtc_btc in", values, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcNotIn(List<Integer> values) {
			addCriterion("realbtc_btc not in", values, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcBetween(Integer value1, Integer value2) {
			addCriterion("realbtc_btc between", value1, value2, "realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcBtcNotBetween(Integer value1, Integer value2) {
			addCriterion("realbtc_btc not between", value1, value2,
					"realbtcBtc");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeIsNull() {
			addCriterion("realbtc_datetime is null");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeIsNotNull() {
			addCriterion("realbtc_datetime is not null");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeEqualTo(Date value) {
			addCriterion("realbtc_datetime =", value, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeNotEqualTo(Date value) {
			addCriterion("realbtc_datetime <>", value, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeGreaterThan(Date value) {
			addCriterion("realbtc_datetime >", value, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("realbtc_datetime >=", value, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeLessThan(Date value) {
			addCriterion("realbtc_datetime <", value, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeLessThanOrEqualTo(Date value) {
			addCriterion("realbtc_datetime <=", value, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeIn(List<Date> values) {
			addCriterion("realbtc_datetime in", values, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeNotIn(List<Date> values) {
			addCriterion("realbtc_datetime not in", values, "realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeBetween(Date value1, Date value2) {
			addCriterion("realbtc_datetime between", value1, value2,
					"realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcDatetimeNotBetween(Date value1, Date value2) {
			addCriterion("realbtc_datetime not between", value1, value2,
					"realbtcDatetime");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInIsNull() {
			addCriterion("realbtc_address_in is null");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInIsNotNull() {
			addCriterion("realbtc_address_in is not null");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInEqualTo(String value) {
			addCriterion("realbtc_address_in =", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInNotEqualTo(String value) {
			addCriterion("realbtc_address_in <>", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInGreaterThan(String value) {
			addCriterion("realbtc_address_in >", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInGreaterThanOrEqualTo(String value) {
			addCriterion("realbtc_address_in >=", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInLessThan(String value) {
			addCriterion("realbtc_address_in <", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInLessThanOrEqualTo(String value) {
			addCriterion("realbtc_address_in <=", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInLike(String value) {
			addCriterion("realbtc_address_in like", value, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInNotLike(String value) {
			addCriterion("realbtc_address_in not like", value,
					"realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInIn(List<String> values) {
			addCriterion("realbtc_address_in in", values, "realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInNotIn(List<String> values) {
			addCriterion("realbtc_address_in not in", values,
					"realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInBetween(String value1, String value2) {
			addCriterion("realbtc_address_in between", value1, value2,
					"realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressInNotBetween(String value1,
				String value2) {
			addCriterion("realbtc_address_in not between", value1, value2,
					"realbtcAddressIn");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutIsNull() {
			addCriterion("realbtc_address_out is null");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutIsNotNull() {
			addCriterion("realbtc_address_out is not null");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutEqualTo(String value) {
			addCriterion("realbtc_address_out =", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutNotEqualTo(String value) {
			addCriterion("realbtc_address_out <>", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutGreaterThan(String value) {
			addCriterion("realbtc_address_out >", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutGreaterThanOrEqualTo(String value) {
			addCriterion("realbtc_address_out >=", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutLessThan(String value) {
			addCriterion("realbtc_address_out <", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutLessThanOrEqualTo(String value) {
			addCriterion("realbtc_address_out <=", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutLike(String value) {
			addCriterion("realbtc_address_out like", value, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutNotLike(String value) {
			addCriterion("realbtc_address_out not like", value,
					"realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutIn(List<String> values) {
			addCriterion("realbtc_address_out in", values, "realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutNotIn(List<String> values) {
			addCriterion("realbtc_address_out not in", values,
					"realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutBetween(String value1, String value2) {
			addCriterion("realbtc_address_out between", value1, value2,
					"realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andRealbtcAddressOutNotBetween(String value1,
				String value2) {
			addCriterion("realbtc_address_out not between", value1, value2,
					"realbtcAddressOut");
			return (Criteria) this;
		}

		public Criteria andTxidIsNull() {
			addCriterion("txid is null");
			return (Criteria) this;
		}

		public Criteria andTxidIsNotNull() {
			addCriterion("txid is not null");
			return (Criteria) this;
		}

		public Criteria andTxidEqualTo(String value) {
			addCriterion("txid =", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotEqualTo(String value) {
			addCriterion("txid <>", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidGreaterThan(String value) {
			addCriterion("txid >", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidGreaterThanOrEqualTo(String value) {
			addCriterion("txid >=", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidLessThan(String value) {
			addCriterion("txid <", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidLessThanOrEqualTo(String value) {
			addCriterion("txid <=", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidLike(String value) {
			addCriterion("txid like", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotLike(String value) {
			addCriterion("txid not like", value, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidIn(List<String> values) {
			addCriterion("txid in", values, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotIn(List<String> values) {
			addCriterion("txid not in", values, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidBetween(String value1, String value2) {
			addCriterion("txid between", value1, value2, "txid");
			return (Criteria) this;
		}

		public Criteria andTxidNotBetween(String value1, String value2) {
			addCriterion("txid not between", value1, value2, "txid");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIsNull() {
			addCriterion("member_idx is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIsNotNull() {
			addCriterion("member_idx is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdxEqualTo(Integer value) {
			addCriterion("member_idx =", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotEqualTo(Integer value) {
			addCriterion("member_idx <>", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxGreaterThan(Integer value) {
			addCriterion("member_idx >", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxGreaterThanOrEqualTo(Integer value) {
			addCriterion("member_idx >=", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxLessThan(Integer value) {
			addCriterion("member_idx <", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxLessThanOrEqualTo(Integer value) {
			addCriterion("member_idx <=", value, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxIn(List<Integer> values) {
			addCriterion("member_idx in", values, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotIn(List<Integer> values) {
			addCriterion("member_idx not in", values, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxBetween(Integer value1, Integer value2) {
			addCriterion("member_idx between", value1, value2, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdxNotBetween(Integer value1, Integer value2) {
			addCriterion("member_idx not between", value1, value2, "memberIdx");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("member_id is null");
			return (Criteria) this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("member_id is not null");
			return (Criteria) this;
		}

		public Criteria andMemberIdEqualTo(String value) {
			addCriterion("member_id =", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotEqualTo(String value) {
			addCriterion("member_id <>", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThan(String value) {
			addCriterion("member_id >", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("member_id >=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThan(String value) {
			addCriterion("member_id <", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(String value) {
			addCriterion("member_id <=", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdLike(String value) {
			addCriterion("member_id like", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotLike(String value) {
			addCriterion("member_id not like", value, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdIn(List<String> values) {
			addCriterion("member_id in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotIn(List<String> values) {
			addCriterion("member_id not in", values, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdBetween(String value1, String value2) {
			addCriterion("member_id between", value1, value2, "memberId");
			return (Criteria) this;
		}

		public Criteria andMemberIdNotBetween(String value1, String value2) {
			addCriterion("member_id not between", value1, value2, "memberId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_REALBTC
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 29 16:30:43 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}