package com.ints.common.model;

import java.util.Date;

public class TaRealbtc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.realbtc_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer realbtcIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.realbtc_type
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String realbtcType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.realbtc_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer realbtcBtc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.realbtc_datetime
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Date realbtcDatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.realbtc_address_in
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String realbtcAddressIn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.realbtc_address_out
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String realbtcAddressOut;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.txid
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String txid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private Integer memberIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TA_REALBTC.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	private String memberId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.realbtc_idx
	 * @return  the value of TA_REALBTC.realbtc_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getRealbtcIdx() {
		return realbtcIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.realbtc_idx
	 * @param realbtcIdx  the value for TA_REALBTC.realbtc_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRealbtcIdx(Integer realbtcIdx) {
		this.realbtcIdx = realbtcIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.realbtc_type
	 * @return  the value of TA_REALBTC.realbtc_type
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getRealbtcType() {
		return realbtcType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.realbtc_type
	 * @param realbtcType  the value for TA_REALBTC.realbtc_type
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRealbtcType(String realbtcType) {
		this.realbtcType = realbtcType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.realbtc_btc
	 * @return  the value of TA_REALBTC.realbtc_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getRealbtcBtc() {
		return realbtcBtc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.realbtc_btc
	 * @param realbtcBtc  the value for TA_REALBTC.realbtc_btc
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRealbtcBtc(Integer realbtcBtc) {
		this.realbtcBtc = realbtcBtc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.realbtc_datetime
	 * @return  the value of TA_REALBTC.realbtc_datetime
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Date getRealbtcDatetime() {
		return realbtcDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.realbtc_datetime
	 * @param realbtcDatetime  the value for TA_REALBTC.realbtc_datetime
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRealbtcDatetime(Date realbtcDatetime) {
		this.realbtcDatetime = realbtcDatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.realbtc_address_in
	 * @return  the value of TA_REALBTC.realbtc_address_in
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getRealbtcAddressIn() {
		return realbtcAddressIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.realbtc_address_in
	 * @param realbtcAddressIn  the value for TA_REALBTC.realbtc_address_in
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRealbtcAddressIn(String realbtcAddressIn) {
		this.realbtcAddressIn = realbtcAddressIn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.realbtc_address_out
	 * @return  the value of TA_REALBTC.realbtc_address_out
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getRealbtcAddressOut() {
		return realbtcAddressOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.realbtc_address_out
	 * @param realbtcAddressOut  the value for TA_REALBTC.realbtc_address_out
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setRealbtcAddressOut(String realbtcAddressOut) {
		this.realbtcAddressOut = realbtcAddressOut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.txid
	 * @return  the value of TA_REALBTC.txid
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getTxid() {
		return txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.txid
	 * @param txid  the value for TA_REALBTC.txid
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setTxid(String txid) {
		this.txid = txid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.member_idx
	 * @return  the value of TA_REALBTC.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public Integer getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.member_idx
	 * @param memberIdx  the value for TA_REALBTC.member_idx
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberIdx(Integer memberIdx) {
		this.memberIdx = memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TA_REALBTC.member_id
	 * @return  the value of TA_REALBTC.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TA_REALBTC.member_id
	 * @param memberId  the value for TA_REALBTC.member_id
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}
}