package com.ints.common.model;

import java.util.Date;

public class TaWonRequest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.won_request_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Integer wonRequestIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.won_request_krw
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Integer wonRequestKrw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.won_request_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Date wonRequestDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.won_request_response_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Date wonRequestResponseDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.won_request_response_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private String wonRequestResponseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.member_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private Integer memberIdx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.member_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private String memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.member_bank
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private String memberBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TA_WON_REQUEST.member_bank_account
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    private String memberBankAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.won_request_idx
     *
     * @return the value of TA_WON_REQUEST.won_request_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Integer getWonRequestIdx() {
        return wonRequestIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.won_request_idx
     *
     * @param wonRequestIdx the value for TA_WON_REQUEST.won_request_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setWonRequestIdx(Integer wonRequestIdx) {
        this.wonRequestIdx = wonRequestIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.won_request_krw
     *
     * @return the value of TA_WON_REQUEST.won_request_krw
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Integer getWonRequestKrw() {
        return wonRequestKrw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.won_request_krw
     *
     * @param wonRequestKrw the value for TA_WON_REQUEST.won_request_krw
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setWonRequestKrw(Integer wonRequestKrw) {
        this.wonRequestKrw = wonRequestKrw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.won_request_datetime
     *
     * @return the value of TA_WON_REQUEST.won_request_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Date getWonRequestDatetime() {
        return wonRequestDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.won_request_datetime
     *
     * @param wonRequestDatetime the value for TA_WON_REQUEST.won_request_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setWonRequestDatetime(Date wonRequestDatetime) {
        this.wonRequestDatetime = wonRequestDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.won_request_response_datetime
     *
     * @return the value of TA_WON_REQUEST.won_request_response_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Date getWonRequestResponseDatetime() {
        return wonRequestResponseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.won_request_response_datetime
     *
     * @param wonRequestResponseDatetime the value for TA_WON_REQUEST.won_request_response_datetime
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setWonRequestResponseDatetime(Date wonRequestResponseDatetime) {
        this.wonRequestResponseDatetime = wonRequestResponseDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.won_request_response_id
     *
     * @return the value of TA_WON_REQUEST.won_request_response_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getWonRequestResponseId() {
        return wonRequestResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.won_request_response_id
     *
     * @param wonRequestResponseId the value for TA_WON_REQUEST.won_request_response_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setWonRequestResponseId(String wonRequestResponseId) {
        this.wonRequestResponseId = wonRequestResponseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.member_idx
     *
     * @return the value of TA_WON_REQUEST.member_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Integer getMemberIdx() {
        return memberIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.member_idx
     *
     * @param memberIdx the value for TA_WON_REQUEST.member_idx
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setMemberIdx(Integer memberIdx) {
        this.memberIdx = memberIdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.member_id
     *
     * @return the value of TA_WON_REQUEST.member_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.member_id
     *
     * @param memberId the value for TA_WON_REQUEST.member_id
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.member_bank
     *
     * @return the value of TA_WON_REQUEST.member_bank
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getMemberBank() {
        return memberBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.member_bank
     *
     * @param memberBank the value for TA_WON_REQUEST.member_bank
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setMemberBank(String memberBank) {
        this.memberBank = memberBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TA_WON_REQUEST.member_bank_account
     *
     * @return the value of TA_WON_REQUEST.member_bank_account
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getMemberBankAccount() {
        return memberBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TA_WON_REQUEST.member_bank_account
     *
     * @param memberBankAccount the value for TA_WON_REQUEST.member_bank_account
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setMemberBankAccount(String memberBankAccount) {
        this.memberBankAccount = memberBankAccount;
    }
}