package com.ints.common.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaWonRequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public TaWonRequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWonRequestIdxIsNull() {
            addCriterion("won_request_idx is null");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxIsNotNull() {
            addCriterion("won_request_idx is not null");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxEqualTo(Integer value) {
            addCriterion("won_request_idx =", value, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxNotEqualTo(Integer value) {
            addCriterion("won_request_idx <>", value, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxGreaterThan(Integer value) {
            addCriterion("won_request_idx >", value, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("won_request_idx >=", value, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxLessThan(Integer value) {
            addCriterion("won_request_idx <", value, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxLessThanOrEqualTo(Integer value) {
            addCriterion("won_request_idx <=", value, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxIn(List<Integer> values) {
            addCriterion("won_request_idx in", values, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxNotIn(List<Integer> values) {
            addCriterion("won_request_idx not in", values, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxBetween(Integer value1, Integer value2) {
            addCriterion("won_request_idx between", value1, value2, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("won_request_idx not between", value1, value2, "wonRequestIdx");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwIsNull() {
            addCriterion("won_request_krw is null");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwIsNotNull() {
            addCriterion("won_request_krw is not null");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwEqualTo(Integer value) {
            addCriterion("won_request_krw =", value, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwNotEqualTo(Integer value) {
            addCriterion("won_request_krw <>", value, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwGreaterThan(Integer value) {
            addCriterion("won_request_krw >", value, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwGreaterThanOrEqualTo(Integer value) {
            addCriterion("won_request_krw >=", value, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwLessThan(Integer value) {
            addCriterion("won_request_krw <", value, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwLessThanOrEqualTo(Integer value) {
            addCriterion("won_request_krw <=", value, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwIn(List<Integer> values) {
            addCriterion("won_request_krw in", values, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwNotIn(List<Integer> values) {
            addCriterion("won_request_krw not in", values, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwBetween(Integer value1, Integer value2) {
            addCriterion("won_request_krw between", value1, value2, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestKrwNotBetween(Integer value1, Integer value2) {
            addCriterion("won_request_krw not between", value1, value2, "wonRequestKrw");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeIsNull() {
            addCriterion("won_request_datetime is null");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeIsNotNull() {
            addCriterion("won_request_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeEqualTo(Date value) {
            addCriterion("won_request_datetime =", value, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeNotEqualTo(Date value) {
            addCriterion("won_request_datetime <>", value, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeGreaterThan(Date value) {
            addCriterion("won_request_datetime >", value, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("won_request_datetime >=", value, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeLessThan(Date value) {
            addCriterion("won_request_datetime <", value, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("won_request_datetime <=", value, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeIn(List<Date> values) {
            addCriterion("won_request_datetime in", values, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeNotIn(List<Date> values) {
            addCriterion("won_request_datetime not in", values, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeBetween(Date value1, Date value2) {
            addCriterion("won_request_datetime between", value1, value2, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("won_request_datetime not between", value1, value2, "wonRequestDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeIsNull() {
            addCriterion("won_request_response_datetime is null");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeIsNotNull() {
            addCriterion("won_request_response_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeEqualTo(Date value) {
            addCriterion("won_request_response_datetime =", value, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeNotEqualTo(Date value) {
            addCriterion("won_request_response_datetime <>", value, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeGreaterThan(Date value) {
            addCriterion("won_request_response_datetime >", value, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("won_request_response_datetime >=", value, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeLessThan(Date value) {
            addCriterion("won_request_response_datetime <", value, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("won_request_response_datetime <=", value, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeIn(List<Date> values) {
            addCriterion("won_request_response_datetime in", values, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeNotIn(List<Date> values) {
            addCriterion("won_request_response_datetime not in", values, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeBetween(Date value1, Date value2) {
            addCriterion("won_request_response_datetime between", value1, value2, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("won_request_response_datetime not between", value1, value2, "wonRequestResponseDatetime");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdIsNull() {
            addCriterion("won_request_response_id is null");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdIsNotNull() {
            addCriterion("won_request_response_id is not null");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdEqualTo(String value) {
            addCriterion("won_request_response_id =", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdNotEqualTo(String value) {
            addCriterion("won_request_response_id <>", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdGreaterThan(String value) {
            addCriterion("won_request_response_id >", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdGreaterThanOrEqualTo(String value) {
            addCriterion("won_request_response_id >=", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdLessThan(String value) {
            addCriterion("won_request_response_id <", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdLessThanOrEqualTo(String value) {
            addCriterion("won_request_response_id <=", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdLike(String value) {
            addCriterion("won_request_response_id like", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdNotLike(String value) {
            addCriterion("won_request_response_id not like", value, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdIn(List<String> values) {
            addCriterion("won_request_response_id in", values, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdNotIn(List<String> values) {
            addCriterion("won_request_response_id not in", values, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdBetween(String value1, String value2) {
            addCriterion("won_request_response_id between", value1, value2, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andWonRequestResponseIdNotBetween(String value1, String value2) {
            addCriterion("won_request_response_id not between", value1, value2, "wonRequestResponseId");
            return (Criteria) this;
        }

        public Criteria andMemberIdxIsNull() {
            addCriterion("member_idx is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdxIsNotNull() {
            addCriterion("member_idx is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdxEqualTo(Integer value) {
            addCriterion("member_idx =", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxNotEqualTo(Integer value) {
            addCriterion("member_idx <>", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxGreaterThan(Integer value) {
            addCriterion("member_idx >", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_idx >=", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxLessThan(Integer value) {
            addCriterion("member_idx <", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxLessThanOrEqualTo(Integer value) {
            addCriterion("member_idx <=", value, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxIn(List<Integer> values) {
            addCriterion("member_idx in", values, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxNotIn(List<Integer> values) {
            addCriterion("member_idx not in", values, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxBetween(Integer value1, Integer value2) {
            addCriterion("member_idx between", value1, value2, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdxNotBetween(Integer value1, Integer value2) {
            addCriterion("member_idx not between", value1, value2, "memberIdx");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("member_id like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("member_id not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberBankIsNull() {
            addCriterion("member_bank is null");
            return (Criteria) this;
        }

        public Criteria andMemberBankIsNotNull() {
            addCriterion("member_bank is not null");
            return (Criteria) this;
        }

        public Criteria andMemberBankEqualTo(String value) {
            addCriterion("member_bank =", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankNotEqualTo(String value) {
            addCriterion("member_bank <>", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankGreaterThan(String value) {
            addCriterion("member_bank >", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankGreaterThanOrEqualTo(String value) {
            addCriterion("member_bank >=", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankLessThan(String value) {
            addCriterion("member_bank <", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankLessThanOrEqualTo(String value) {
            addCriterion("member_bank <=", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankLike(String value) {
            addCriterion("member_bank like", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankNotLike(String value) {
            addCriterion("member_bank not like", value, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankIn(List<String> values) {
            addCriterion("member_bank in", values, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankNotIn(List<String> values) {
            addCriterion("member_bank not in", values, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankBetween(String value1, String value2) {
            addCriterion("member_bank between", value1, value2, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankNotBetween(String value1, String value2) {
            addCriterion("member_bank not between", value1, value2, "memberBank");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountIsNull() {
            addCriterion("member_bank_account is null");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountIsNotNull() {
            addCriterion("member_bank_account is not null");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountEqualTo(String value) {
            addCriterion("member_bank_account =", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountNotEqualTo(String value) {
            addCriterion("member_bank_account <>", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountGreaterThan(String value) {
            addCriterion("member_bank_account >", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("member_bank_account >=", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountLessThan(String value) {
            addCriterion("member_bank_account <", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountLessThanOrEqualTo(String value) {
            addCriterion("member_bank_account <=", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountLike(String value) {
            addCriterion("member_bank_account like", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountNotLike(String value) {
            addCriterion("member_bank_account not like", value, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountIn(List<String> values) {
            addCriterion("member_bank_account in", values, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountNotIn(List<String> values) {
            addCriterion("member_bank_account not in", values, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountBetween(String value1, String value2) {
            addCriterion("member_bank_account between", value1, value2, "memberBankAccount");
            return (Criteria) this;
        }

        public Criteria andMemberBankAccountNotBetween(String value1, String value2) {
            addCriterion("member_bank_account not between", value1, value2, "memberBankAccount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 29 17:30:03 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}