package com.ints.common.dao;

import com.ints.common.model.TaAdminMng;
import com.ints.common.model.TaAdminMngExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaAdminMngMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaAdminMngExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaAdminMngExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer adminMngIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaAdminMng record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaAdminMng record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaAdminMng> selectByExample(TaAdminMngExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaAdminMng selectByPrimaryKey(Integer adminMngIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaAdminMng record,
			@Param("example") TaAdminMngExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaAdminMng record,
			@Param("example") TaAdminMngExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaAdminMng record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ADMIN_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaAdminMng record);

	TaAdminMng selectAdminMngById(String id);
	
	
}

