package com.ints.common.dao;

import com.ints.common.model.TaAskMng;
import com.ints.common.model.TaAskMngExample;
import com.ints.common.model.TaFaqMng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaAskMngMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer askMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaAskMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaAskMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaAskMng> selectByExampleWithBLOBs(TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaAskMng> selectByExample(TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaAskMng selectByPrimaryKey(Integer askMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaAskMng record,
			@Param("example") TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TaAskMng record,
			@Param("example") TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaAskMng record,
			@Param("example") TaAskMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaAskMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TaAskMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_ASK_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaAskMng record);
	List<TaAskMng> selectQnaList(@Param("page")int page);
	List<TaAskMng> selectSearchQnaList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
	int selectQnaListCnt();
	int selectSearchQnaListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
	
}