package com.ints.common.dao;

import com.ints.common.model.TaBoardReply;
import com.ints.common.model.TaBoardReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaBoardReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer replyIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaBoardReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaBoardReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaBoardReply> selectByExampleWithBLOBs(TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaBoardReply> selectByExample(TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaBoardReply selectByPrimaryKey(Integer replyIdx);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaBoardReply record,
			@Param("example") TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TaBoardReply record,
			@Param("example") TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaBoardReply record,
			@Param("example") TaBoardReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaBoardReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TaBoardReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_BOARD_REPLY
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaBoardReply record);
}