package com.ints.common.dao;

import com.ints.common.model.TaFaqMng;
import com.ints.common.model.TaFaqMngExample;
import com.ints.common.model.TaNoticeMng;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaFaqMngMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer faqMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaFaqMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaFaqMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaFaqMng> selectByExampleWithBLOBs(TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaFaqMng> selectByExample(TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaFaqMng selectByPrimaryKey(Integer faqMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaFaqMng record,
			@Param("example") TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TaFaqMng record,
			@Param("example") TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaFaqMng record,
			@Param("example") TaFaqMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaFaqMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TaFaqMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_FAQ_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaFaqMng record);
	List<TaFaqMng> selectFaqList(@Param("page")int page);
	List<TaFaqMng> selectSearchFaqList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
	int selectFaqListCnt();
	int selectSearchFaqListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
	
}