package com.ints.common.dao;

import com.ints.common.model.TaKrwRequest;
import com.ints.common.model.TaKrwRequestExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaKrwRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int countByExample(TaKrwRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int deleteByExample(TaKrwRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int deleteByPrimaryKey(Integer krwRequestIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int insert(TaKrwRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int insertSelective(TaKrwRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    List<TaKrwRequest> selectByExample(TaKrwRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    TaKrwRequest selectByPrimaryKey(Integer krwRequestIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByExampleSelective(@Param("record") TaKrwRequest record, @Param("example") TaKrwRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByExample(@Param("record") TaKrwRequest record, @Param("example") TaKrwRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByPrimaryKeySelective(TaKrwRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_KRW_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByPrimaryKey(TaKrwRequest record);
    
    List<TaKrwRequest> selectKrwRequestList(@Param("page")int page);
    List<TaKrwRequest> selectSearchedKrwRequestList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
    int selectKrwRequestListCnt();
    int selectSearchedKrwRequestListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
    
}