package com.ints.common.dao;

import com.ints.common.model.TaMember;
import com.ints.common.model.TaMemberWallet;
import com.ints.common.model.TaMemberWalletExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaMemberWalletMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaMemberWalletExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaMemberWalletExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer memberWalletIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaMemberWallet record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaMemberWallet record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaMemberWallet> selectByExample(TaMemberWalletExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaMemberWallet selectByPrimaryKey(Integer memberWalletIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaMemberWallet record,
			@Param("example") TaMemberWalletExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaMemberWallet record,
			@Param("example") TaMemberWalletExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaMemberWallet record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_MEMBER_WALLET
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaMemberWallet record);
	//With index value
	List<TaMemberWallet> selectMemberWalletList(@Param("page")int page,@Param("memberIdx")int memberIdx);
    List<TaMemberWallet> selectSearchedMemberWalletList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page, @Param("memberIdx")int memberIdx);
    int selectMemberWalletListCnt(@Param("memberIdx")int memberIdx);
    int selectSearchedMemberWalletCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("memberIdx")int memberIdx);
    
    //without index value
    List<TaMemberWallet> selectMemberWalletListWoi(@Param("page")int page);
    List<TaMemberWallet> selectSearchedMemberWalletListWoi(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
    int selectMemberWalletListCntWoi();
    int selectSearchedMemberWalletCntWoi(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
    
    
}