package com.ints.common.dao;

import com.ints.common.model.TaNoticeMng;
import com.ints.common.model.TaNoticeMngExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaNoticeMngMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer noticeMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaNoticeMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaNoticeMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaNoticeMng> selectByExampleWithBLOBs(TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaNoticeMng> selectByExample(TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaNoticeMng selectByPrimaryKey(Integer noticeMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaNoticeMng record,
			@Param("example") TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TaNoticeMng record,
			@Param("example") TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaNoticeMng record,
			@Param("example") TaNoticeMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaNoticeMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TaNoticeMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_NOTICE_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaNoticeMng record);
	List<TaNoticeMng> selectNoticeList(@Param("page")int page);
	List<TaNoticeMng> selectSearchNoticeList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
	int selectNoticeListCnt();
	int selectSearchNoticeListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
	
}