package com.ints.common.dao;

import com.ints.common.model.TaFaqMng;
import com.ints.common.model.TaPopupMng;
import com.ints.common.model.TaPopupMngExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaPopupMngMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer popupMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaPopupMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaPopupMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaPopupMng> selectByExampleWithBLOBs(TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaPopupMng> selectByExample(TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaPopupMng selectByPrimaryKey(Integer popupMngIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaPopupMng record,
			@Param("example") TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") TaPopupMng record,
			@Param("example") TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaPopupMng record,
			@Param("example") TaPopupMngExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaPopupMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(TaPopupMng record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_POPUP_MNG
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaPopupMng record);
	List<TaPopupMng> selectPopupList(@Param("page")int page);
	List<TaPopupMng> selectSearchPopupList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
	int selectPopupListCnt();
	int selectSearchPopupListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
	
}