package com.ints.common.dao;

import com.ints.common.model.TaMemberWallet;
import com.ints.common.model.TaRealbtc;
import com.ints.common.model.TaRealbtcExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaRealbtcMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int countByExample(TaRealbtcExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByExample(TaRealbtcExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int deleteByPrimaryKey(Integer realbtcIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insert(TaRealbtc record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int insertSelective(TaRealbtc record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	List<TaRealbtc> selectByExample(TaRealbtcExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	TaRealbtc selectByPrimaryKey(Integer realbtcIdx);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TaRealbtc record,
			@Param("example") TaRealbtcExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByExample(@Param("record") TaRealbtc record,
			@Param("example") TaRealbtcExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKeySelective(TaRealbtc record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TA_REALBTC
	 * @mbggenerated  Tue Jul 29 17:30:03 KST 2014
	 */
	int updateByPrimaryKey(TaRealbtc record);
	List<TaRealbtc> selectRealbtcList(@Param("page")int page);
    List<TaRealbtc> selectSearchedRealbtcList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
    int selectRealbtcListCnt();
    int selectSearchedRealbtcListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
   
}