package com.ints.common.dao;


import com.ints.common.model.TaWonRequest;
import com.ints.common.model.TaWonRequestExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TaWonRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int countByExample(TaWonRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int deleteByExample(TaWonRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int deleteByPrimaryKey(Integer wonRequestIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int insert(TaWonRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int insertSelective(TaWonRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    List<TaWonRequest> selectByExample(TaWonRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    TaWonRequest selectByPrimaryKey(Integer wonRequestIdx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByExampleSelective(@Param("record") TaWonRequest record, @Param("example") TaWonRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByExample(@Param("record") TaWonRequest record, @Param("example") TaWonRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByPrimaryKeySelective(TaWonRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TA_WON_REQUEST
     *
     * @mbggenerated Tue Jul 29 17:30:03 KST 2014
     */
    int updateByPrimaryKey(TaWonRequest record);
    
    List<TaWonRequest> selectWonRequestList(@Param("page")int page);
    List<TaWonRequest> selectSearchedWonRequestList(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate, @Param("page")int page);
    int selectWonRequestListCnt();
    int selectSearchedWonRequestListCnt(@Param("searchWord")String searchWord, @Param("startDate")String startDate, @Param("endDate")String endDate);
    
}